# tests/modules/keys-manifest-tests.nix — keys-manifest.json invariants.
#
# Validates the manifest structure, key patterns, uniqueness, and schema
# compliance.  The manifest is generated by apply scripts from decrypted
# SOPS secrets and consumed by sops.nix and ai.nix at Nix eval time.
#
# NOTE: keys-manifest.json is a runtime artifact generated by apply.sh /
# apply.ps1.  It does not exist on a fresh checkout.  Tests that require
# the file use tryEval and are skipped when the file is absent.

let
  manifestPath = ../../src/modules/ai/keys-manifest.json;
  manifestExists = builtins.pathExists manifestPath;
  manifest =
    if manifestExists then
      builtins.fromJSON (builtins.readFile manifestPath)
    else
      { availableKeys = [ ]; };
  inherit (import ../lib.nix) assert';

  availableKeys = manifest.availableKeys or [ ];

  # Pattern: keys must match ai_<provider>_api_key or ai_<provider>_api_key_<N>
  keyPattern = builtins.match "^ai_[a-z0-9_]+_api_key(_[0-9]+)?$";

  # builtins.unique unavailable in pure eval; manual dedup via foldl'.
  uniqueKeys = builtins.foldl' (
    acc: k: if builtins.elem k acc then acc else acc ++ [ k ]
  ) [ ] availableKeys;
in
{
  # === Manifest existence ===

  # The manifest is generated at apply time; skip all structural tests when
  # absent rather than hard-failing the Nix test step on a fresh checkout.
  test_manifest_file_exists = if manifestExists then null else null;

  # === Manifest structure (conditional on file existence) ===

  test_manifest_has_available_keys = assert' (
    !manifestExists || manifest ? availableKeys
  ) "manifest must have an availableKeys field";

  test_available_keys_is_list = assert' (
    !manifestExists || builtins.isList availableKeys
  ) "availableKeys must be a list";

  # === Key pattern validation ===

  test_all_keys_match_pattern = assert' (
    !manifestExists || builtins.all (k: keyPattern k != null) availableKeys
  ) "all keys must match ai_<provider>_api_key[_<N>] pattern";

  # === Uniqueness ===

  test_no_duplicate_keys = assert' (
    !manifestExists || builtins.length uniqueKeys == builtins.length availableKeys
  ) "availableKeys must have no duplicates";

  # === Key count matches static registry ===

  test_key_count_matches_registry = assert' (
    !manifestExists || builtins.length availableKeys == 6
  ) "manifest must contain exactly 6 keys";

  test_expected_providers_present = assert' (
    !manifestExists
    || builtins.all (k: builtins.elem k availableKeys) [
      "ai_command_code_api_key"
      "ai_openrouter_api_key"
      "ai_opencode_go_api_key"
      "ai_opencode_go_api_key_1"
      "ai_opencode_zen_api_key"
      "ai_opencode_zen_api_key_1"
    ]
  ) "all 6 expected provider keys must be present in manifest";
}
