---
camilla_host: "127.0.0.1"
camilla_port: 1234
bind_address: "127.0.0.1"
port: 5005
ssl_certificate: null
ssl_private_key: null
gui_config_file: null
config_dir: "~/.config/camilladsp/configs"
coeff_dir: "~/.config/camilladsp/coeffs"
default_config: "~/.config/camilladsp/config.yml"
statefile_path: "~/.config/camilladsp/configs/state.yml"
log_file: "~/Library/Logs/nucleus/camilladsp/camilladsp.log"
on_set_active_config: null
on_get_active_config: null
supported_capture_types: null
supported_playback_types: null
