devices:
  samplerate: 48000
  chunksize: 1024
  capture:
    type: Wasapi
    channels: 2
    device: "Speakers (Realtek Audio)"
    loopback: true
    format: F32
  playback:
    type: Wasapi
    channels: 2
    device: "Speakers (Realtek Audio)"
    format: F32
