---
description: null
devices:
  adjust_period: null
  capture:
    channels: 2
    device: BlackHole 2ch
    format: null
    labels: null
    type: Wasapi
  capture_samplerate: null
  chunksize: 1024
  enable_rate_adjust: null
  multithreaded: null
  playback:
    channels: 2
    device: null
    exclusive: null
    format: null
    type: Wasapi
  queuelimit: null
  rate_measure_interval: null
  resampler: null
  samplerate: 44100
  silence_threshold: null
  silence_timeout: null
  stop_on_rate_change: null
  target_level: null
  volume_limit: null
  volume_ramp_time: null
  worker_threads: null
filters:
  crossover highpass:
    description: null
    parameters:
      freq: 300
      order: 4
      type: LinkwitzRileyHighpass
    type: BiquadCombo
  crossover lowpass:
    description: null
    parameters:
      freq: 300
      order: 4
      type: LinkwitzRileyLowpass
    type: BiquadCombo
  subsonic highpass:
    description: null
    parameters:
      freq: 22
      order: 4
      type: ButterworthHighpass
    type: BiquadCombo
mixers:
  split to 4 channels:
    channels:
      in: 2
      out: 4
    description: null
    labels: null
    mapping:
      - dest: 0
        mute: null
        sources:
          - channel: 0
            gain: 0
            inverted: null
            mute: null
            scale: null
      - dest: 1
        mute: null
        sources:
          - channel: 1
            gain: 0
            inverted: null
            mute: null
            scale: null
      - dest: 2
        mute: null
        sources:
          - channel: 0
            gain: 0
            inverted: null
            mute: null
            scale: null
      - dest: 3
        mute: null
        sources:
          - channel: 1
            gain: 0
            inverted: null
            mute: null
            scale: null
  sum to 2 channels:
    channels:
      in: 4
      out: 2
    description: null
    labels: null
    mapping:
      - dest: 0
        mute: null
        sources:
          - channel: 0
            gain: 0
            inverted: null
            mute: null
            scale: null
          - channel: 2
            gain: 0
            inverted: null
            mute: null
            scale: null
      - dest: 1
        mute: null
        sources:
          - channel: 1
            gain: 0
            inverted: null
            mute: null
            scale: null
          - channel: 3
            gain: 0
            inverted: null
            mute: null
            scale: null
pipeline:
  - bypassed: null
    channels:
      - 0
      - 1
    description: null
    names:
      - subsonic highpass
    type: Filter
  - bypassed: null
    description: null
    name: split to 4 channels
    type: Mixer
  - bypassed: null
    channels:
      - 0
      - 1
    description: null
    names:
      - crossover lowpass
    type: Filter
  - bypassed: null
    channels:
      - 2
      - 3
    description: null
    names:
      - crossover highpass
    type: Filter
  - bypassed: null
    description: null
    name: low gate
    type: Processor
  - bypassed: null
    description: null
    name: low compressor
    type: Processor
  - bypassed: null
    description: null
    name: mid-high gate
    type: Processor
  - bypassed: null
    description: null
    name: mid-high compressor
    type: Processor
  - bypassed: null
    description: null
    name: sum to 2 channels
    type: Mixer
  - bypassed: null
    description: null
    name: master limiter
    type: Processor
processors:
  low compressor:
    description: null
    parameters:
      attack: 0.08
      channels: 4
      clip_limit: null
      factor: 2
      makeup_gain: 8
      monitor_channels:
        - 0
        - 1
      process_channels:
        - 0
        - 1
      release: 0.6
      soft_clip: null
      threshold: -32
    type: Compressor
  low gate:
    description: null
    parameters:
      attack: 0.05
      attenuation: 10
      channels: 4
      monitor_channels:
        - 0
        - 1
      process_channels:
        - 0
        - 1
      release: 2.5
      threshold: -54
    type: NoiseGate
  master limiter:
    description: null
    parameters:
      attack: 0.001
      channels: 2
      clip_limit: 0
      factor: 20
      makeup_gain: 0
      monitor_channels:
        - 0
        - 1
      process_channels:
        - 0
        - 1
      release: 0.1
      soft_clip: true
      threshold: -1.5
    type: Compressor
  mid-high compressor:
    description: null
    parameters:
      attack: 0.025
      channels: 4
      clip_limit: null
      factor: 3.5
      makeup_gain: 15
      monitor_channels:
        - 2
        - 3
      process_channels:
        - 2
        - 3
      release: 0.8
      soft_clip: null
      threshold: -36
    type: Compressor
  mid-high gate:
    description: null
    parameters:
      attack: 0.02
      attenuation: 15
      channels: 4
      monitor_channels:
        - 2
        - 3
      process_channels:
        - 2
        - 3
      release: 2.5
      threshold: -56
    type: NoiseGate
title: 2-band automatic gain control (-14 LUFS)
