#!/usr/bin/env bash
# src/scripts/install-prek-hooks.sh — Install prek Git hooks for a repository.
#
# Installs repository-local Git hooks for repos that opt into prek via
# prek.toml. mkApplyApp bundles pkgs.prek in runtimeInputs so first-run
# `nix run .#apply` can install hooks without host-global PATH state.
#
# Arguments:
#   --repo-root <path>  Override detected repository root (default: auto-detected via resolve_nucleus_root).
#
# Environment variables:
#   NUCLEUS_REPO_ROOT  Override the detected repository root path (default: auto-detected).
#
# Exit conditions:
#   0 on success (hooks installed or already present); 1 on error.
set -euo pipefail

SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"

if [ -f "$SCRIPT_DIR/lib.sh" ]; then
  . "$SCRIPT_DIR/lib.sh"
else
  usage_std() {
    printf 'usage: %s %s\n' "$1" "${2:-}"
    [ "$#" -gt 2 ] && printf '  %s\n' "$3"
  }
  resolve_nucleus_root() {
    [ -n "${NUCLEUS_REPO_ROOT:-}" ] && [ -d "$NUCLEUS_REPO_ROOT" ] && { printf '%s\n' "$NUCLEUS_REPO_ROOT"; return 0; }
    printf '%s\n' "${HOME}/dev/nucleus"
  }
fi

# Install repository-local Git hooks for repos that opt into prek.
# mkApplyApp bundles pkgs.prek in runtimeInputs so first-run `nix run .#apply`
# can install hooks without depending on host-global PATH state.
# WHY git rev-parse: handles .git as file (submodules, worktrees) + directory
# (normal repos). Avoids silent failure in workspace-variant scenarios.
_ephi_repo_root=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --repo-root)
      _ephi_repo_root="$2"
      shift 2
      ;;
    *)
      usage_std "$(basename "$0")" "[--repo-root <path>]" "Install prek Git hooks for a repository"
      exit 2
      ;;
  esac
done

if [ -z "$_ephi_repo_root" ]; then
  _ephi_repo_root="$(resolve_nucleus_root)"
fi
_ephi_config_path="$_ephi_repo_root/prek.toml"

if [ ! -f "$_ephi_config_path" ]; then
  exit 0
fi

# Detect .git directory; works for normal repos, submodules, and worktrees.
_ephi_git_dir=$(cd "$_ephi_repo_root" && git rev-parse --git-dir 2>/dev/null) || exit 0

# Convert relative git-dir paths to absolute (git rev-parse --git-dir may
# return relative paths like .git or ../../../.git in nested submodules).
case "$_ephi_git_dir" in
  /*)
    # Absolute path: use as-is
    ;;
  *)
    # Relative path: join with repo root to make absolute
    _ephi_git_dir="$_ephi_repo_root/$_ephi_git_dir"
    ;;
esac

_ephi_hook_dir="$_ephi_git_dir/hooks"

# Skip noisy reinstalls when any existing hook file is already a prek-
# generated shim.  Hook sets can vary by repository, so do not hardcode
# specific filenames here.
if [ -d "$_ephi_hook_dir" ]; then
  for _ephi_hook_path in "$_ephi_hook_dir"/*; do
    [ -f "$_ephi_hook_path" ] || continue
    if grep -qF '# File generated by prek' "$_ephi_hook_path"; then
      exit 0
    fi
  done
fi

if ! command -v prek >/dev/null 2>&1; then
  printf '%s\n' "prek: prek binary not found; skipping hook installation for $_ephi_repo_root" >&2
  exit 0
fi

printf '%s\n' "prek: installing hooks in $_ephi_repo_root"
if ! (cd "$_ephi_repo_root" && prek install); then
  printf '%s\n' "prek: failed to install hooks in $_ephi_repo_root" >&2
  exit 1
fi
