#!/usr/bin/env bash
# Installs repository-local Git hooks for repos that opt into prek via
# prek.toml. mkApplyApp bundles pkgs.prek in runtimeInputs so first-run
# `nix run .#apply` can install hooks without host-global PATH state.

set -euo pipefail

SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"

# shellcheck disable=SC1091
. "$SCRIPT_DIR/lib.sh"

_ephi_repo_root=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --repo-root)
      _ephi_repo_root="$2"
      shift 2
      ;;
    *)
      usage_std "$(basename "$0")" "[--repo-root <path>]" "Install prek Git hooks for a repository"
      exit 2
      ;;
  esac
done

if [ -z "$_ephi_repo_root" ]; then
  _ephi_repo_root="$(resolve_nucleus_root)"
fi
_ephi_config_path="$_ephi_repo_root/prek.toml"

if [ ! -f "$_ephi_config_path" ]; then
  exit 0
fi

_ephi_git_dir=$(cd "$_ephi_repo_root" && git rev-parse --git-dir 2>/dev/null) || exit 0

case "$_ephi_git_dir" in
  /*)
    ;;
  *)
    _ephi_git_dir="$_ephi_repo_root/$_ephi_git_dir"
    ;;
esac

_ephi_hook_dir="$_ephi_git_dir/hooks"

# Skip noisy reinstalls when any existing hook file is already a prek-
# generated shim.  Hook sets can vary by repository, so do not hardcode
# specific filenames here.
if [ -d "$_ephi_hook_dir" ]; then
  for _ephi_hook_path in "$_ephi_hook_dir"/*; do
    [ -f "$_ephi_hook_path" ] || continue
    if grep -qF '# File generated by prek' "$_ephi_hook_path"; then
      exit 0
    fi
  done
fi

if ! command -v prek >/dev/null 2>&1; then
  printf '%s\n' "prek: prek binary not found; skipping hook installation for $_ephi_repo_root" >&2
  exit 0
fi

printf '%s\n' "prek: installing hooks in $_ephi_repo_root"
if ! (cd "$_ephi_repo_root" && prek install); then
  printf '%s\n' "prek: failed to install hooks in $_ephi_repo_root" >&2
  exit 1
fi
