#!/usr/bin/env sh
# src/scripts/install-prek-hooks.sh — Install prek Git hooks for a repository
# Args: $1 — absolute path to the repository root
# Exit: 0 success, 1 error
set -eu

# Install repository-local Git hooks for repos that opt into prek.
# mkApplyApp bundles pkgs.prek in runtimeInputs so first-run `nix run .#apply`
# can install hooks without depending on host-global PATH state.
# WHY git rev-parse: handles .git as file (submodules, worktrees) + directory
# (normal repos). Avoids silent failure in workspace-variant scenarios.
_ephi_repo_root="$1"
_ephi_config_path="$_ephi_repo_root/prek.toml"

if [ ! -f "$_ephi_config_path" ]; then
  exit 0
fi

# Detect .git directory; works for normal repos, submodules, and worktrees.
_ephi_git_dir=$(cd "$_ephi_repo_root" && git rev-parse --git-dir 2>/dev/null) || exit 0

# Convert relative git-dir paths to absolute (git rev-parse --git-dir may
# return relative paths like .git or ../../../.git in nested submodules).
case "$_ephi_git_dir" in
  /*)
    # Absolute path: use as-is
    ;;
  *)
    # Relative path: join with repo root to make absolute
    _ephi_git_dir="$_ephi_repo_root/$_ephi_git_dir"
    ;;
esac

_ephi_hook_dir="$_ephi_git_dir/hooks"

# Skip noisy reinstalls when any existing hook file is already a prek-
# generated shim.  Hook sets can vary by repository, so do not hardcode
# specific filenames here.
if [ -d "$_ephi_hook_dir" ]; then
  for _ephi_hook_path in "$_ephi_hook_dir"/*; do
    [ -f "$_ephi_hook_path" ] || continue
    if grep -qF '# File generated by prek' "$_ephi_hook_path"; then
      exit 0
    fi
  done
fi

if ! command -v prek >/dev/null 2>&1; then
  printf '%s\n' "prek: prek binary not found; skipping hook installation for $_ephi_repo_root" >&2
  exit 0
fi

printf '%s\n' "prek: installing hooks in $_ephi_repo_root"
if ! (cd "$_ephi_repo_root" && prek install); then
  printf '%s\n' "prek: failed to install hooks in $_ephi_repo_root" >&2
  exit 1
fi
