# modules/pwsh.nix — PowerShell profile management for POSIX hosts.
#
# Manages ~/.config/powershell/Microsoft.PowerShell_profile.ps1 so that
# cross-host pwsh behavior mirrors the managed block written by
# Sync-NucleusShellProfile on Windows (src/hosts/windows/modules/sync-shellprofile.ps1).
# Keeping both in sync makes PowerShell behavior consistent across all three
# host types when pwsh is invoked on macOS or NixOS.
{ lib, pkgs, ... }:
let
  # Keep the same fallback tool inventory as the POSIX zsh profile so managed
  # pwsh sessions can work in repositories that do not provide direnv/Nix hooks.
  defaultDevTools = pkgs.symlinkJoin {
    name = "default-dev-tools";
    paths = [
      pkgs.bun
      pkgs.cargo
      pkgs.prek
      pkgs.rustc
      pkgs.uv
    ];
  };

  # Profile content mirroring the Windows managed block in shell.ps1.
  # Using a Nix ''...'' string so the file is written verbatim; single
  # dollar signs and PowerShell variables ($line, $cursor, etc.) do not
  # need escaping because Nix only interpolates ${...} (braced) forms.
  profileContent = ''
    # This file is managed by nucleus (src/modules/pwsh.nix).
    # Manual edits will be overwritten on the next `nix run .#apply`.

    # direnv: load per-directory environments defined in .envrc files.
    if (Get-Command direnv -ErrorAction SilentlyContinue) {
      (& direnv hook pwsh) | Out-String | Invoke-Expression
    }

    # Keep a user-scoped fallback toolchain available when the current project
    # does not provide a direnv/devShell entrypoint.
    $env:NUCLEUS_DEFAULT_DEV_BIN = "${defaultDevTools}/bin"
    $env:NUCLEUS_DEFAULT_DEV_ENV = "1"

    # PSReadLine: predictive history completion and menu-style tab expansion.
    # Guards with module availability probe so the profile loads on hosts where
    # PSReadLine is absent or an unexpected version is installed.
    if (Get-Module -ListAvailable -Name PSReadLine) {
      Import-Module PSReadLine
      Set-PSReadLineOption -PredictionSource History
      Set-PSReadLineOption -PredictionViewStyle ListView
      Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete
    }

    # zoxide: smart directory navigation learned from visit history.
    if (Get-Command zoxide -ErrorAction SilentlyContinue) {
      Invoke-Expression (& zoxide init powershell | Out-String)
    }

    # LLVM/Clang toolchain defaults for cross-host compiler parity.
    $env:CC = "clang"
    $env:CXX = "clang++"
    $env:LD = "ld.lld"

    # prek: install repository-local Git hooks automatically the first time a
    # shell session enters a repo that opted into prek via prek.toml.
    # The hook first checks for the canonical generated shims so already-
    # provisioned repos stay quiet across new shell sessions, then falls back
    # to a per-session cache to avoid repeated installs after the first run.
    $global:__nucleusPrekCheckedRepos = @{}
    $global:__nucleusPrekInstallInProgress = $false
    function Test-PrekHooksInstalled {
      param(
        [Parameter(Mandatory = $true)]
        [string]$RepositoryRoot
      )

      $hookDir = Join-Path $RepositoryRoot ".git/hooks"
      if (-not (Test-Path -Path $hookDir -PathType Container)) {
        return $false
      }

      foreach ($hookPath in Get-ChildItem -Path $hookDir -File) {
        if (Select-String -Path $hookPath.FullName -Pattern '# File generated by prek' -SimpleMatch -Quiet) {
          return $true
        }
      }

      return $false
    }
    function Invoke-PrekHookInstallIfNeeded {
      # Get-Command is a presence probe here; absence is expected on unmanaged
      # shells, and the function returns immediately after the check.
      if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
        return
      }
      if (-not (Get-Command prek -ErrorAction SilentlyContinue)) {
        return
      }

      # git rev-parse is a repo-membership probe here; suppress the expected
      # stderr from non-repository directories and branch on the result.
      $repoRootOutput = & git -C (Get-Location).Path rev-parse --show-toplevel 2>$null
      if ($null -eq $repoRootOutput) {
        return
      }
      $repoRoot = ($repoRootOutput | Out-String).Trim()
      if ([string]::IsNullOrWhiteSpace($repoRoot)) {
        return
      }

      $prekConfigPath = Join-Path $repoRoot "prek.toml"
      if (-not (Test-Path -Path $prekConfigPath -PathType Leaf)) {
        return
      }
      if ($global:__nucleusPrekInstallInProgress) {
        return
      }
      if ($global:__nucleusPrekCheckedRepos.ContainsKey($repoRoot)) {
        return
      }
      if (Test-PrekHooksInstalled -RepositoryRoot $repoRoot) {
        $global:__nucleusPrekCheckedRepos[$repoRoot] = $true
        return
      }

      $global:__nucleusPrekInstallInProgress = $true
      Write-Host "prek: installing hooks in $repoRoot" -ForegroundColor Cyan
      Push-Location $repoRoot
      try {
        & prek install
        if ($LASTEXITCODE -ne 0) {
          throw "prek install failed with exit code $LASTEXITCODE"
        }

        $global:__nucleusPrekCheckedRepos[$repoRoot] = $true
      }
      catch {
        Write-Warning "prek: failed to install hooks in $repoRoot — $($_.Exception.Message)"
      }
      finally {
        $global:__nucleusPrekInstallInProgress = $false
        Pop-Location
      }
    }

    if (-not $global:__nucleusPrekPromptWrapped) {
      $global:__nucleusPrekPromptWrapped = $true
      $global:__nucleusPrekPreviousPrompt = if (Test-Path Function:\prompt) {
        (Get-Command prompt -CommandType Function).ScriptBlock
      } else {
        $null
      }

      function global:prompt {
        Invoke-PrekHookInstallIfNeeded
        if ($null -ne $global:__nucleusPrekPreviousPrompt) {
          & $global:__nucleusPrekPreviousPrompt
        } else {
          "PS $(Get-Location)> "
        }
      }
    }

    Invoke-PrekHookInstallIfNeeded

    # fzf: fuzzy history search on Ctrl+R via a PSReadLine key handler.
    # Reads the PSReadLine history file directly so all sessions are searchable.
    # Guard requires both fzf and PSReadLine to avoid silently failing on a
    # host where fzf is installed but the module is missing.
    if ((Get-Command fzf -ErrorAction SilentlyContinue) -and (Get-Module -ListAvailable -Name PSReadLine)) {
      Set-PSReadLineKeyHandler -Key "Ctrl+r" -ScriptBlock {
        $line = $null
        $cursor = $null
        [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
        $histFile = (Get-PSReadLineOption).HistorySavePath
        $selected = Get-Content -Path $histFile -ErrorAction SilentlyContinue |
          Where-Object { $_ } | Sort-Object -Unique |
          & fzf --tac --no-sort --height 40% --query $line
        if ($LASTEXITCODE -eq 0 -and $selected) {
          [Microsoft.PowerShell.PSConsoleReadLine]::RevertLine()
          [Microsoft.PowerShell.PSConsoleReadLine]::Insert($selected)
        }
      }
    }

    function g { & git @Args }
    function ga { & git add @Args }
    function gc { & git commit @Args }
    function gca { & git commit --amend @Args }
    function gco { & git checkout @Args }
    function gd { & git diff @Args }
    function gll { & git log --oneline --decorate --graph @Args }
    function gp { & git push @Args }
    function gpl { & git pull @Args }

    function Invoke-NucleusGhostscript {
      if (Get-Command gs -ErrorAction SilentlyContinue) {
        & gs @Args
        return
      }
      if (Get-Command gswin64c -ErrorAction SilentlyContinue) {
        & gswin64c @Args
        return
      }
      if (Get-Command gswin32c -ErrorAction SilentlyContinue) {
        & gswin32c @Args
        return
      }
      throw "Ghostscript CLI not found. Expected one of: gs, gswin64c, gswin32c"
    }

    # Ghostscript PDF optimization presets.
    # CompatibilityLevel is pinned to 2.0 (latest as of 2026-05); bump when a
    # newer PDF compatibility target is released by Ghostscript.
    function gs-pdf-opt-default  { Invoke-NucleusGhostscript -sDEVICE=pdfwrite -dCompatibilityLevel=2.0 -dPDFSETTINGS=/default  -dNOPAUSE -dQUIET -dBATCH @Args }
    function gs-pdf-opt-ebook    { Invoke-NucleusGhostscript -sDEVICE=pdfwrite -dCompatibilityLevel=2.0 -dPDFSETTINGS=/ebook    -dNOPAUSE -dQUIET -dBATCH @Args }
    function gs-pdf-opt-prepress { Invoke-NucleusGhostscript -sDEVICE=pdfwrite -dCompatibilityLevel=2.0 -dPDFSETTINGS=/prepress -dNOPAUSE -dQUIET -dBATCH @Args }
    function gs-pdf-opt-printer  { Invoke-NucleusGhostscript -sDEVICE=pdfwrite -dCompatibilityLevel=2.0 -dPDFSETTINGS=/printer  -dNOPAUSE -dQUIET -dBATCH @Args }
    function gs-pdf-opt-screen   { Invoke-NucleusGhostscript -sDEVICE=pdfwrite -dCompatibilityLevel=2.0 -dPDFSETTINGS=/screen   -dNOPAUSE -dQUIET -dBATCH @Args }

    function gst { & git status @Args }

    # la/ll: prefer eza for colour, icons, and extended metadata; fall back to
    # Get-ChildItem when eza is absent so the profile loads on unmanaged machines.
    if (Get-Command eza -ErrorAction SilentlyContinue) {
      function la { & eza -la @Args }
      function ll { & eza -la @Args }
    } else {
      function la { Get-ChildItem -Force @Args }
      function ll { Get-ChildItem -Force @Args }
    }

    function v { & nvim @Args }

    # System-wide Python ban: redirect python/pip to warnings so users are
    # guided to scoped alternatives instead of modifying the system environment.
    function python {
      Write-Host "shell: system-wide Python is banned to prevent accidental modifications." -ForegroundColor Yellow
      Write-Host "         Use one of these approaches instead:" -ForegroundColor Yellow
      Write-Host "         - nix develop     (activate project devShell with scoped Python)" -ForegroundColor Yellow
      Write-Host "         - uv run <cmd>    (run Python via uv package manager)" -ForegroundColor Yellow
      Write-Host "         - uv venv         (create per-project venv managed by uv)" -ForegroundColor Yellow
      Write-Host "         - ./venv/bin/python (use pre-existing project venv)" -ForegroundColor Yellow
      return 1
    }
    function python3 {
      python @Args
    }
    function pip {
      Write-Host "shell: system-wide pip is banned to prevent breaking system dependencies." -ForegroundColor Yellow
      Write-Host "         Use one of these approaches instead:" -ForegroundColor Yellow
      Write-Host "         - nix develop     (activate project devShell with scoped Python+pip)" -ForegroundColor Yellow
      Write-Host "         - uv pip install  (use uv to manage project dependencies)" -ForegroundColor Yellow
      Write-Host "         - uv venv         (create per-project venv managed by uv)" -ForegroundColor Yellow
      Write-Host "         - ./venv/bin/pip  (use pre-existing project venv)" -ForegroundColor Yellow
      return 1
    }
    function pip3 {
      pip @Args
    }

    # Route managed development tools through either an active direnv context
    # or the user-scoped fallback toolchain for unmanaged repositories.
    function Invoke-NucleusManagedDevTool {
      param(
        [Parameter(Mandatory = $true)]
        [string]$ToolName,

        [Parameter(Mandatory = $false)]
        [string]$FallbackBinDirectory,

        [Parameter(ValueFromRemainingArguments = $true)]
        [object[]]$ToolArguments
      )

      if ($env:DIRENV_DIR) {
        $application = Get-Command -Name $ToolName -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($null -ne $application) {
          & $application.Source @ToolArguments
          return $true
        }
      }

      if (-not [string]::IsNullOrWhiteSpace($FallbackBinDirectory)) {
        $fallbackToolPath = Join-Path $FallbackBinDirectory $ToolName
        if (Test-Path -Path $fallbackToolPath -PathType Leaf) {
          & $fallbackToolPath @ToolArguments
          return $true
        }
      }

      return $false
    }

    # System-wide build tool block: redirect bun/cargo/rustc/uv to warnings.
    # These tools are installed globally for system package management only.
    # When DIRENV_DIR is set, a direnv environment (devShell) is active; when it
    # is absent, fall back to the managed default toolchain installed by apply.
    function bun {
      if (Invoke-NucleusManagedDevTool -ToolName "bun" -FallbackBinDirectory $env:NUCLEUS_DEFAULT_DEV_BIN @Args) {
        return
      }
      Write-Host "shell: managed bun is unavailable right now." -ForegroundColor Yellow
      Write-Host "         For development, use one of these managed entrypoints:" -ForegroundColor Yellow
      Write-Host "         - Enter a project directory with .envrc (direnv auto-loads the devShell)" -ForegroundColor Yellow
      Write-Host "         - Or use the user-scoped default toolchain installed by nucleus apply" -ForegroundColor Yellow
      Write-Host "         Shell shortcuts ni/nr/nx also work inside a devShell." -ForegroundColor Yellow
      return 1
    }
    function cargo {
      if (Invoke-NucleusManagedDevTool -ToolName "cargo" -FallbackBinDirectory $env:NUCLEUS_DEFAULT_DEV_BIN @Args) {
        return
      }
      Write-Host "shell: managed cargo is unavailable right now." -ForegroundColor Yellow
      Write-Host "         For Rust development, use one of these managed entrypoints:" -ForegroundColor Yellow
      Write-Host "         - Enter a project directory with .envrc (direnv auto-loads the devShell)" -ForegroundColor Yellow
      Write-Host "         - Or use the user-scoped default toolchain installed by nucleus apply" -ForegroundColor Yellow
      return 1
    }
    function rustc {
      if (Invoke-NucleusManagedDevTool -ToolName "rustc" -FallbackBinDirectory $env:NUCLEUS_DEFAULT_DEV_BIN @Args) {
        return
      }
      Write-Host "shell: managed rustc is unavailable right now." -ForegroundColor Yellow
      Write-Host "         For Rust development, use one of these managed entrypoints:" -ForegroundColor Yellow
      Write-Host "         - Enter a project directory with .envrc (direnv auto-loads the devShell)" -ForegroundColor Yellow
      Write-Host "         - Or use the user-scoped default toolchain installed by nucleus apply" -ForegroundColor Yellow
      return 1
    }
    function uv {
      if (Invoke-NucleusManagedDevTool -ToolName "uv" -FallbackBinDirectory $env:NUCLEUS_DEFAULT_DEV_BIN @Args) {
        return
      }
      Write-Host "shell: managed uv is unavailable right now." -ForegroundColor Yellow
      Write-Host "         For Python development, use one of these managed entrypoints:" -ForegroundColor Yellow
      Write-Host "         - Enter a project directory with .envrc (direnv auto-loads the devShell)" -ForegroundColor Yellow
      Write-Host "         - Or use the user-scoped default toolchain installed by nucleus apply" -ForegroundColor Yellow
      return 1
    }
  '';
in
{
  # Place the PowerShell profile at the CurrentUserCurrentHost location for
  # interactive pwsh sessions.  On macOS and Linux, pwsh reads this path from
  # $PROFILE.CurrentUserCurrentHost at startup.
  home.file.".config/powershell/Microsoft.PowerShell_profile.ps1".text = profileContent;

  # Install PSScriptAnalyzer for PowerShell linting if pwsh is available.
  # This enables the lint phase in scripts/check-pwsh.ps1.
  home.activation.installPwshScriptAnalyzer = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    _pwsh="${pkgs.powershell}/bin/pwsh"
    if [ -x "$_pwsh" ]; then
      "$_pwsh" -NoProfile -Command "
        if (-not (Get-Module -ListAvailable -Name PSScriptAnalyzer)) {
          Write-Host 'installPwshScriptAnalyzer: installing PSScriptAnalyzer...' -ForegroundColor Cyan
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser -AllowClobber -ErrorAction Stop
        }
      "
    fi
  '';
}
