<#
.SYNOPSIS
    Pester parity tests verifying Windows env vars match the Nix catalog.
.DESCRIPTION
    Evaluates the Nix centralized env var catalog (src/modules/lib/env-vars.nix)
    and compares every Windows-relevant variable against the Windows DSC
    registry (user/env.dsc.yml) and Sync-ShellProfile.ps1.

    Designed to fail if:
    - A catalog var expected on Windows has no DSC or profile entry.
    - A DSC var has no counterpart in the Nix catalog (would drift silently).
.NOTES
    Requires: Nix-powered environment to evaluate the catalog (nix eval or
    prebuilt JSON manifest).  The manifest is generated by
    tests/integration/env-parity-tests.nix.
    Exit codes: 0 on success; 1 on failure
#>

BeforeAll {
  $ErrorActionPreference = "Stop"
  $WarningPreference = "SilentlyContinue"

  # Paths
  $RepoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..\..\..\")
  $DscFile = Join-Path $RepoRoot "src\hosts\Windows\user\env.dsc.yml"
  $ManifestFile = Join-Path $RepoRoot "result\env-parity-manifest.json"
  $CatalogNixFile = Join-Path $RepoRoot "src\modules\lib\env-vars.nix"

  # ---- Helpers ----

  # Parse DSC YAML and return all Environment resource names.
  function Get-DscEnvVarNames {
    param ([string]$DscPath)
    if (-not (Test-Path $DscPath)) {
      throw "DSC file not found: $DscPath"
    }
    $yaml = Get-Content -Raw -Path $DscPath
    # Minimal YAML parser: extract name from Microsoft.Windows.Environment/Variable resources.
    $resources = [regex]::Matches($yaml, '(?s)resource:\s*Microsoft\.Windows\.Environment/Variable.*?settings:\s*\n(.*?)(?=\n    - resource|\n    #|$)')
    $names = @()
    foreach ($match in $resources) {
      $settingsBlock = $match.Groups[1].Value
      $nameMatch = [regex]::Match($settingsBlock, 'name:\s*(.+)')
      if ($nameMatch.Success) {
        $names += $nameMatch.Groups[1].Value.Trim()
      }
    }
    return $names
  }

  # Evaluate the Nix catalog JSON manifest.
  # Uses pre-built result if available, otherwise runs nix eval.
  function Get-NixCatalogManifest {
    param ([string]$ManifestPath)
    if (Test-Path $ManifestPath) {
      return Get-Content -Raw -Path $ManifestPath | ConvertFrom-Json
    }
    # Fall back to nix eval
    $nixTestFile = Join-Path $RepoRoot "src\tests\integration\env-parity-tests.nix"
    $evalExpr = "(import ""$nixTestFile"" { }).manifest"
    # undoc-supp: nix eval prints progress to stderr
    $json = & nix eval --impure --expr $evalExpr --json 2>$null
    if ($LASTEXITCODE -ne 0) {
      throw "nix eval failed. Ensure nix is available and the expression is correct."
    }
    return $json | ConvertFrom-Json
  }

  # Extract profile-only vars (CC, CXX, LD) from Sync-ShellProfile.ps1.
  function Get-ProfileEnvVarNames {
    $profilePath = Join-Path $RepoRoot "src\hosts\Windows\modules\user\Sync-ShellProfile.ps1"
    $content = Get-Content -Raw -Path $profilePath
    $names = @()
    # Match $env:VARNAME patterns in the PowerShell heredoc
    $matches = [regex]::Matches($content, '\$env:(\w+)\s*=')
    foreach ($m in $matches) {
      $names += $m.Groups[1].Value
    }
    return $names | Select-Object -Unique
  }

  # Build expected Windows var name list from the catalog.
  function Get-ExpectedWindowsVarNames {
    param ($Manifest)
    $expected = @()
    foreach ($entry in $Manifest) {
      # Only vars relevant to Windows: those with explicit Windows override, or
      # those that include Windows in their hosts list (default: all hosts).
      $entry.hosts -contains "Windows" -or
      ($null -eq $entry.override) -and
      ($null -eq $entry.hosts -or $entry.hosts.Count -eq 0)
    }
    # Exclude macOS-only vars
    $macOnlyVars = @("DEVELOPER_DIR", "SDKROOT", "LIBRARY_PATH", "NIX_SSL_CERT_FILE", "NUCLEUS_REPO_ROOT")
    return $expected | Where-Object { $_ -notin $macOnlyVars }
  }

  # Read apply.ps1 content (used by multiple tests).
  function Get-ApplyPs1Content {
    $applyPath = Join-Path $RepoRoot "src\hosts\Windows\apply.ps1"
    return Get-Content -Raw -Path $applyPath
  }
}

Describe "Windows env var parity with Nix catalog" {
  Context "DSC parity" {
    It "env.dsc.yml exists and is readable" {
      $DscFile | Should -Exist
    }

    It "catalog manifest evaluates successfully" {
      { $script:Manifest = Get-NixCatalogManifest -ManifestPath $ManifestFile } | Should -Not -Throw
      $script:Manifest | Should -Not -BeNullOrEmpty
    }

    It "every catalog var expected on Windows has a DSC entry" {
      $dscVars = Get-DscEnvVarNames -DscPath $DscFile
      $expectedVars = Get-ExpectedWindowsVarNames -Manifest $script:Manifest

      $missing = $expectedVars | Where-Object { $_ -notin $dscVars }
      if ($missing.Count -gt 0) {
        Write-Warning "Missing DSC env vars: $($missing -join ', ')"
      }
      $missing.Count | Should -Be 0 -Because "every Nix catalog variable expected on Windows should have a DSC Environment resource"
    }

    It "every DSC Env resource has a Nix catalog counterpart" {
      $dscVars = Get-DscEnvVarNames -DscPath $DscFile
      $catalogNames = $script:Manifest | ForEach-Object { $_.name }
      # Exclude expected Windows-only vars
      $windowsOnlyVars = @("HOME", "NIX_PATH")
      $catalogNames += $windowsOnlyVars

      $extra = $dscVars | Where-Object { $_ -notin $catalogNames }
      if ($extra.Count -gt 0) {
        Write-Warning "DSC env vars without Nix catalog entry: $($extra -join ', ')"
      }
      $extra.Count | Should -Be 0 -Because "every DSC Environment resource should have a Nix catalog counterpart"
    }
  }

  Context "Shell profile parity" {
    It "Sync-ShellProfile.ps1 sets CC, CXX, LD matching the catalog" {
      $profileVars = Get-ProfileEnvVarNames
      $profileVars | Should -Contain "CC"
      $profileVars | Should -Contain "CXX"
      $profileVars | Should -Contain "LD"

      # Verify values match the catalog
      $ccEntry = $script:Manifest | Where-Object { $_.name -eq "CC" } | Select-Object -First 1
      $ccEntry | Should -Not -BeNullOrEmpty
      $ccEntry.scope | Should -Be "shell-only"
    }
  }

  Context "apply.ps1 parity" {
    It "apply.ps1 sets NUCLEUS_HOST to Windows" {
      $content = Get-ApplyPs1Content
      $content | Should -Match ('NUCLEUS_HOST.*=.*"Windows"')
    }

    It "apply.ps1 persists NUCLEUS_REPO_ROOT via SetEnvironmentVariable (Machine scope)" {
      $content = Get-ApplyPs1Content
      # NUCLEUS_REPO_ROOT is set dynamically per-activation (not via DSC),
      # so the test verifies the Machine-scope SetEnvironmentVariable call
      # exists rather than checking a specific value.
      $content | Should -Match ([regex]::Escape('[Environment]::SetEnvironmentVariable("NUCLEUS_REPO_ROOT", $repoRoot, "Machine")'))
    }

    It "apply.ps1 does not broadcast env change notification (removed)" {
      $content = Get-ApplyPs1Content
      $content | Should -Not -Match ('Send-NucleusEnvChangeNotification')
    }
  }

  Context "apply.ps1 NUCLEUS_HOST handling" {
    It "sets process-level env var only (no registry persistence in apply.ps1)" {
      $content = Get-ApplyPs1Content
      $content | Should -Match ([regex]::Escape('$env:NUCLEUS_HOST = "Windows"'))
    }

    It "does not persist NUCLEUS_HOST via SetEnvironmentVariable (handled by system/env.dsc.yml)" {
      $content = Get-ApplyPs1Content
      $content | Should -Not -Match ([regex]::Escape('[Environment]::SetEnvironmentVariable("NUCLEUS_HOST"'))
    }

    It "does not read persisted NUCLEUS_HOST value (delegated to DSC)" {
      $content = Get-ApplyPs1Content
      $content | Should -Not -Match ([regex]::Escape('GetEnvironmentVariable("NUCLEUS_HOST"'))
    }

    It "post-DSC does not clear User-scope NUCLEUS_HOST (never written in first place)" {
      $content = Get-ApplyPs1Content
      $content | Should -Not -Match ([regex]::Escape('[Environment]::SetEnvironmentVariable("NUCLEUS_HOST", $null, "User")'))
    }
  }

  Context "apply.ps1 NUCLEUS_REPO_ROOT handling" {
    It "reads current Machine scope value for compare" {
      $content = Get-ApplyPs1Content
      $content | Should -Match ([regex]::Escape('[Environment]::GetEnvironmentVariable("NUCLEUS_REPO_ROOT", "Machine")'))
      $content | Should -Match ([regex]::Escape('if ($existingRoot -ne $repoRoot)'))
    }

    It "writes Machine scope directly if value changed (no post-DSC promotion needed)" {
      $content = Get-ApplyPs1Content
      $content | Should -Match ([regex]::Escape('[Environment]::SetEnvironmentVariable("NUCLEUS_REPO_ROOT", $repoRoot, "Machine")'))
      $content | Should -Not -Match ([regex]::Escape('Write-Warning "apply: cannot promote NUCLEUS_REPO_ROOT to Machine scope'))
    }

    It "clears stale User scope value after Machine scope write" {
      $content = Get-ApplyPs1Content
      $content | Should -Match ([regex]::Escape('[Environment]::SetEnvironmentVariable("NUCLEUS_REPO_ROOT", $null, "User")'))
    }
  }
}
