# Invoke-VMSetup.ps1 — Provisions and configures virtual machines on Windows.
#
# Reads VM definitions from src/modules/VMs.json and creates QCOW2 disk images
# plus QEMU start scripts for each declared VM.  QEMU is installed via the
# Scoop extras bucket (see Invoke-ScoopSetup.ps1).
#
# Disk images are stored at %USERPROFILE%\virtual machines\<name>.qcow2,
# mirroring the ~/virtual machines/<name>.qcow2 path used on POSIX hosts.
# QCOW2 format enables copy-based migration to UTM (macOS) or libvirt (NixOS).
#
# Each VM also gets a start script at
#   %USERPROFILE%\virtual machines\Start-<display>.ps1
# so the user can launch QEMU from a PowerShell terminal without remembering
# the full command line.
#
# Exit: always 0 — VM setup failures do not abort the apply workflow.
# Source: https://www.qemu.org/docs/master/system/invocation.html
function Invoke-VMSetup {
    [CmdletBinding()]
    param(
        # Absolute path to the repository root.
        [Parameter(Mandatory)]
        [string]$RepoRoot,

        # Print planned actions without modifying any state.
        [switch]$DryRun
    )

    $manifest = Join-Path $RepoRoot 'src\modules\VMs.json'

    if (-not (Test-Path $manifest)) {
        Write-Information "VM-setup: manifest not found at $manifest; skipping"
        return
    }

    $vmDef = Get-Content $manifest -Raw | ConvertFrom-Json
    $vmDir = Join-Path $env:USERPROFILE 'virtual machines'

    # Locate qemu-img from the Scoop-managed QEMU installation.
    $scoopQemuDir = Join-Path $env:USERPROFILE 'scoop\apps\qemu\current'
    $qemuImg = Join-Path $scoopQemuDir 'qemu-img.exe'
    if (-not (Test-Path $qemuImg)) {
        # Fall back to PATH in case qemu-img is available another way.
        $qemuImgInPath = Get-Command qemu-img -ErrorAction SilentlyContinue
        if ($qemuImgInPath) {
            $qemuImg = $qemuImgInPath.Source
        } else {
            Write-Information 'VM-setup: qemu-img not found; install QEMU via Scoop (scoop install qemu)'
            $qemuImg = $null
        }
    }

    if (-not $DryRun) {
        New-Item -ItemType Directory -Path $vmDir -Force | Out-Null
    } else {
        Write-Information "VM-setup: [dry-run] New-Item Directory $vmDir"
    }

    foreach ($vm in $vmDef.vms) {
        $diskPath = Join-Path $vmDir "$($vm.name).qcow2"
        $startScript = Join-Path $vmDir "Start-$($vm.display).ps1"

        Write-Information "VM-setup: configuring VM '$($vm.display)'..."

        # Create QCOW2 disk if absent.
        if (Test-Path $diskPath) {
            Write-Information "VM-setup: disk already exists: $diskPath"
        } elseif ($null -ne $qemuImg) {
            $diskSizeArg = "$($vm.diskGiB)G"
            if ($DryRun) {
                Write-Information "VM-setup: [dry-run] & '$qemuImg' create -f qcow2 '$diskPath' $diskSizeArg"
            } else {
                Write-Information "VM-setup: creating QCOW2 disk ($($vm.diskGiB) GiB): $diskPath"
                & $qemuImg create -f qcow2 $diskPath $diskSizeArg
                if ($LASTEXITCODE -ne 0) {
                    Write-Warning "VM-setup: qemu-img failed for '$($vm.name)'; disk not created"
                }
            }
        } else {
            Write-Information "VM-setup: skipping disk creation for '$($vm.name)' (qemu-img unavailable)"
        }

        # Determine the QEMU system binary and machine type based on host arch.
        $hostArch = $env:PROCESSOR_ARCHITECTURE
        if ($hostArch -eq 'ARM64') {
            $qemuSystem = Join-Path $scoopQemuDir 'qemu-system-aarch64.exe'
            $machine = 'virt'
            $cpu = 'host'
        } else {
            $qemuSystem = Join-Path $scoopQemuDir 'qemu-system-x86_64.exe'
            $machine = 'q35'
            $cpu = 'host'
        }

        if ($vm.type -eq 'windows') {
            $display = 'sdl'
            $vga = 'std'
        } else {
            $display = 'sdl'
            $vga = 'virtio'
        }

        # Determine VirtioFS shared directory argument.
        $virtiofsArgs = ''
        if ($vm.shareDevDir) {
            $devDir = Join-Path $env:USERPROFILE 'dev'
            # VirtioFS on Windows requires virtiofsd running separately.
            # Add a placeholder reminder; the start script shows how to launch
            # virtiofsd before starting the guest.
            $virtiofsArgs = @"

# To enable ~/dev directory sharing:
# 1. Start virtiofsd in a separate terminal:
#      virtiofsd --socket-path=\\.\pipe\$($vm.name)-virtiofs --shared-dir="$devDir"
# 2. Then run this script.
# -chardev socket,id=char0,path=\\.\pipe\$($vm.name)-virtiofs ``
# -device vhost-user-fs-pci,chardev=char0,tag=dev ``
# -object memory-backend-file,id=mem,size=$($vm.ramMiB)M,mem-path=/dev/shm,share=on ``
# -numa node,memdev=mem
"@
        }

        # Write a self-contained QEMU start script for this VM.
        $startContent = @"
# Start-$($vm.display).ps1 — Start the '$($vm.display)' QEMU virtual machine.
# Generated by Invoke-VMSetup; re-run `nucleus-VM-setup` to regenerate.
# Attach an ISO for first-time installation:
#   Add: -cdrom 'C:\path\to\install.iso'
#
# Source: https://www.qemu.org/docs/master/system/invocation.html
$virtiofsArgs
& '$qemuSystem' ``
    -name '$($vm.display)' ``
    -machine $machine ``
    -cpu $cpu ``
    -smp $($vm.cpus) ``
    -m $($vm.ramMiB) ``
    -drive file='$diskPath',format=qcow2,if=virtio ``
    -netdev user,id=net0 ``
    -device virtio-net-pci,netdev=net0 ``
    -vga $vga ``
    -display $display ``
    -enable-kvm ``
    -rtc base=localtime ``
    -usb -device usb-tablet
"@

        if ($DryRun) {
            Write-Information "VM-setup: [dry-run] Write start script: $startScript"
        } else {
            Set-Content -Path $startScript -Value $startContent -Encoding UTF8
            Write-Information "VM-setup: start script written: $startScript"
        }

        # Write a configuration reference script for the guest OS.
        $configureScript = Join-Path $vmDir "$($vm.name)-configure.sh"
        $configureContent = switch ($vm.type) {
            'nixos' {
@'
#!/usr/bin/env sh
# Apply the nucleus nixos host configuration inside this VM.
# ~/dev is shared via VirtioFS when shareDevDir=true.
sudo nixos-rebuild switch --flake "$HOME/dev/nucleus/src#nixos"
'@
            }
            'windows' {
@'
#!/usr/bin/env sh
# Apply the nucleus Windows host configuration inside this VM.
# Clone this repository to %USERPROFILE%\dev\nucleus inside the VM, then run:
#   .\src\hosts\windows\apply.ps1
'@
            }
            'macos' {
@'
#!/usr/bin/env sh
# Apply the nucleus macbook host configuration inside this VM.
# Clone this repository to ~/dev/nucleus inside the VM, then run:
#   ~/dev/nucleus/scripts/bootstrap.sh apply
'@
            }
            default { $null }
        }
        if ($null -ne $configureContent) {
            if ($DryRun) {
                Write-Information "VM-setup: [dry-run] Write configure script: $configureScript"
            } else {
                Set-Content -Path $configureScript -Value $configureContent -Encoding UTF8
                Write-Information "VM-setup: configure script written: $configureScript"
            }
        }

        Write-Information "VM-setup: VM '$($vm.display)' setup complete"
    }

    Write-Information 'VM-setup: Windows VM setup complete'
    Write-Information "VM-setup: Disk images at: $vmDir"
    Write-Information 'VM-setup: Run the generated Start-*.ps1 scripts to launch VMs'
    Write-Information 'VM-setup: Attach an ISO (-cdrom flag) for first-time guest OS installation'
}
