# Generated by ensure_env_catalog — do not edit.
{
  keys = [
    {
      name = "key_ai_cline";
      envVar = "KEY_AI_CLINE";
    }
    {
      name = "key_ai_command_code";
      envVar = "KEY_AI_COMMAND_CODE";
    }
    {
      name = "key_ai_opencode_go";
      envVar = "KEY_AI_OPENCODE_GO";
    }
    {
      name = "key_ai_opencode_go_1";
      envVar = "KEY_AI_OPENCODE_GO_1";
    }
    {
      name = "key_ai_opencode_zen";
      envVar = "KEY_AI_OPENCODE_ZEN";
    }
    {
      name = "key_ai_opencode_zen_1";
      envVar = "KEY_AI_OPENCODE_ZEN_1";
    }
    {
      name = "key_ai_openrouter";
      envVar = "KEY_AI_OPENROUTER";
    }
  ];
}
