# Generated by ensure_key_catalog — do not edit.
{
  keys = [
    {
      name = "ai_command_code_api_key";
      envVar = "COMMAND_CODE_API_KEY";
    }
    {
      name = "ai_opencode_go_api_key";
      envVar = "OPENCODE_GO_API_KEY";
    }
    {
      name = "ai_opencode_go_api_key_1";
      envVar = "OPENCODE_GO_API_KEY_1";
    }
    {
      name = "ai_opencode_zen_api_key";
      envVar = "OPENCODE_ZEN_API_KEY";
    }
    {
      name = "ai_opencode_zen_api_key_1";
      envVar = "OPENCODE_ZEN_API_KEY_1";
    }
    {
      name = "ai_openrouter_api_key";
      envVar = "OPENROUTER_API_KEY";
    }
  ];
}
