---
description: null
devices:
  adjust_period: null
  capture:
    channels: 2
    device: BlackHole 2ch
    format: null
    labels: null
    type: Alsa
  capture_samplerate: null
  chunksize: 1024
  enable_rate_adjust: null
  multithreaded: null
  playback:
    channels: 2
    device: null
    exclusive: null
    format: null
    type: Alsa
  queuelimit: null
  rate_measure_interval: null
  resampler: null
  samplerate: 96000
  silence_threshold: null
  silence_timeout: null
  stop_on_rate_change: null
  target_level: null
  volume_limit: null
  volume_ramp_time: null
  worker_threads: null
filters:
  compressor pre-gain:
    description: null
    parameters:
      gain: 30
      inverted: false
      mute: false
      scale: dB
    type: Gain
mixers: {}
pipeline:
  - bypassed: null
    channels: null
    description: null
    names:
      - compressor pre-gain
    type: Filter
  - bypassed: null
    description: null
    name: compressor
    type: Processor
processors:
  compressor:
    description: null
    parameters:
      attack: 0.025
      channels: 2
      clip_limit: 0
      factor: 3.5
      makeup_gain: 12
      monitor_channels: null
      process_channels: null
      release: 0.25
      soft_clip: true
      threshold: -21
    type: Compressor
title: null
