function Sync-TerminalActivation {
  <#
  .SYNOPSIS
    Run activation commands that require user terminal context.

  .DESCRIPTION
    Reads ~/.config/nucleus/terminal-activations.list (generated by the
    write-terminal-activations HM activation step on POSIX hosts).
    On Windows, the manifest is absent by default — the function is a no-op
    unless an external tool populates the file.

    Each non-empty, non-comment line is executed as a command in the current
    shell session, preserving any user-context grants.

  .NOTES
    Environment variables:
      (none)    No environment variables used.

    Exit codes:
      0 on success (or if skip/manifest missing); child process errors are
      logged but do not propagate.
  #>

  $manifestPath = Join-Path -Path $env:USERPROFILE -ChildPath '.config\nucleus\terminal-activations.list'
  if (-not (Test-Path -LiteralPath $manifestPath)) {
    return
  }

  $lines = Get-Content -LiteralPath $manifestPath | Where-Object { $_ -and $_ -notmatch '^\s*#' }
  if ($lines.Count -eq 0) {
    # check-suppress:suppression_doc: best-effort cleanup of empty manifest -- file may already be gone.
    Remove-Item -LiteralPath $manifestPath -Force -ErrorAction SilentlyContinue
    return
  }

  Write-NucleusInfo -CommandName 'terminal-activations' "running $($lines.Count) terminal-context activation(s)..."
  foreach ($line in $lines) {
    $line = $line.Trim()
    if (-not $line) { continue }
    Write-NucleusInfo -CommandName 'terminal-activations' $line
    try {
      # check-suppress:suppression_doc: child process errors are non-fatal for apply.
      & ([ScriptBlock]::Create($line))
    } catch {
      Write-NucleusWarning -CommandName 'terminal-activations' "command exited with error (continuing): $_"
    }
  }
  # check-suppress:suppression_doc: best-effort cleanup -- file may already be deleted by earlier steps or locked.
  Remove-Item -LiteralPath $manifestPath -Force -ErrorAction SilentlyContinue
}
