<#
.SYNOPSIS
  Converge the nucleus-litellm Windows native SCM service.

.DESCRIPTION
  Creates and maintains the `nucleus-litellm` native Windows SCM service
  that starts the LiteLLM AI gateway proxy at boot as SYSTEM.

  The wrapper script under %ProgramData%\nucleus\litellm\ reads API keys from
  %ProgramData%\nucleus\secrets\ and the litellm config from a symlink.
  Secrets are materialised by apply.ps1 via SOPS decryption of system.yml.

  On disable the function removes the SCM service.

.NOTES
  Environment variables:
    (none)    No environment variables used.

  Exit codes:
    0 on success; 1 on error.
#>

function Sync-LiteLLMService {
  <#
  .SYNOPSIS
    Converges the litellm native SCM service.

  .PARAMETER RepoRoot
    Absolute path to the repository root.  Required so the function can locate
    the litellm config source file under src\modules\ai\.

  .PARAMETER Enabled
    Whether the litellm service should exist.  When false, the managed service
    is removed if present.

  .EXAMPLE
    Sync-LiteLLMService -RepoRoot 'C:\Users\admin\nucleus' -Enabled:$true

  .EXAMPLE
    Sync-LiteLLMService -RepoRoot 'C:\Users\admin\nucleus' -Enabled:$false
  #>
  [CmdletBinding()]
  param(
    [Parameter(Mandatory)]
    [string]$RepoRoot,

    [Parameter(Mandatory)]
    [bool]$Enabled
  )

  if (-not (Test-Path -LiteralPath $RepoRoot -PathType Container)) {
    throw "RepoRoot does not exist: $RepoRoot"
  }

  . (Join-Path -Path $PSScriptRoot -ChildPath "..\Set-NucleusService.ps1")

  $ErrorActionPreference = "Stop"
  $serviceName = 'nucleus-litellm'

  if (-not $Enabled) {
    # check-suppress:suppression_doc: probe whether service exists; Get-Service throws when absent.
    $existingService = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
    if ($null -ne $existingService) {
      Remove-NucleusService -Name $serviceName
      Write-NucleusInfo -CommandName 'litellm' "removed SCM service '$serviceName' (disabled)"
    }
    return
  }

  # Find the litellm binary installed by uv.
  # uv tool install places binaries in ~\.local\bin by default.
  $litellmBin = Join-Path -Path $HOME -ChildPath ".local\bin\litellm.exe"
  if (-not (Test-Path -Path $litellmBin -PathType Leaf)) {
    # check-suppress:suppression_doc: probe whether the binary is on PATH; Get-Command throws when absent.
    $litellmCmd = Get-Command -Name "litellm" -ErrorAction SilentlyContinue
    if ($null -eq $litellmCmd) {
      Write-NucleusInfo -CommandName 'litellm' "binary not found; ensure Invoke-UvSetup has installed 'litellm[proxy]'"
      return
    }
    $litellmBin = $litellmCmd.Source
  }

  # Prepare ProgramData directories.
  $programDataDir = Join-Path -Path $env:ProgramData -ChildPath "nucleus\litellm"
  $logDir = Get-NucleusSystemLogDir
  $serviceLogDir = Join-Path -Path $logDir -ChildPath "litellm"
  $secretsDir = Join-Path -Path $env:ProgramData -ChildPath "nucleus\secrets"
  $null = New-Item -Path $secretsDir -ItemType Directory -Force  # check-suppress:suppression_doc: New-Item returns DirectoryInfo, discarded

  . (Join-Path -Path $PSScriptRoot -ChildPath "..\Set-ManagedSymlinkDeleteProtection.ps1")

  # Symlink the config so source edits take effect on service restart without
  # re-running apply.
  $configLink = Join-Path -Path $programDataDir -ChildPath "litellm-config.yml"
  $configSource = Join-Path -Path $RepoRoot -ChildPath "src\modules\ai\litellm-config.yml"
  if (-not (Test-Path -Path $configSource -PathType Leaf)) {
    throw "litellm config source not found: $configSource"
  }
  if (Test-Path -Path $configLink) { Remove-Item -Path $configLink -Force }
  New-Item -Path $configLink -ItemType SymbolicLink -Target $configSource -Force > $null
  Set-ManagedSymlinkDeleteProtection -Context "Sync-LiteLLMService" -Path $configLink

  $logFile = Join-Path -Path $serviceLogDir -ChildPath "combined.log"

  # Data-driven: read the env catalog to discover API keys and their env var
  # mappings.  The catalog is generated by apply.ps1 to the runtime config
  # directory.
  $catalogPath = Join-Path -Path $env:LOCALAPPDATA -ChildPath 'nucleus\env-catalog.json'
  $catalog = if (Test-Path -LiteralPath $catalogPath) {
    Get-Content -Raw -LiteralPath $catalogPath | ConvertFrom-Json
  } else { [PSCustomObject]@{ keys = @() } }

  # Build JSON key-spec array for the wrapper script: [{file, env}, ...]
  $keySpecs = @()
  foreach ($entry in $catalog.keys) {
    $keySpecs += [PSCustomObject]@{ file = $entry.name; env = $entry.envVar }
  }

  $litellmEndpoint = & {
    # check-suppress:suppression_doc: probe -- services.json may not exist yet; $null check handles absence.
    $svc = Get-Content -Raw (Join-Path $RepoRoot 'src/modules/services.json') -ErrorAction SilentlyContinue | ConvertFrom-Json
    if ($svc.litellm.network.default) { $svc.litellm.network.default } else { @{ host = '127.0.0.1'; port = 4000 } }
  }

  # Write a PowerShell wrapper script that sets environment variables then
  # launches litellm.  Using a wrapper file avoids the nested-quoting problem
  # that would arise from embedding this logic inline in sc.exe binPath.
  $wrapperScript = Join-Path -Path $programDataDir -ChildPath "run-litellm.ps1"
  $wrapperContent = Get-Content -Raw (Join-Path -Path $PSScriptRoot -ChildPath "..\scripts\LiteLLM-run.ps1")
  $keySpecsJson = $keySpecs | ConvertTo-Json -Compress
  # Redis env vars for LiteLLM coordination + response cache.
  $redisConfig = & {
    # check-suppress:suppression_doc: probe -- services.json may not exist yet; $null check handles absence.
    $svc = Get-Content -Raw (Join-Path $RepoRoot 'src/modules/services.json') -ErrorAction SilentlyContinue | ConvertFrom-Json
    if ($svc.redis.network.default) { $svc.redis.network.default } else { @{ host = '127.0.0.1'; port = 6379 } }
  }
  $redisHost = $redisConfig.host
  $redisPort = [string]$redisConfig.port
  $wrapperContent = $wrapperContent `
    -replace '__LITELLM_BIN__', $litellmBin `
    -replace '__CONFIG_LINK__', $configLink `
    -replace '__LOGFILE__', $logFile `
    -replace '__HOST__', $($litellmEndpoint.host) `
    -replace '__PORT__', $($litellmEndpoint.port) `
    -replace "'__KEY_SPECS__'", $keySpecsJson `
    -replace "'__REDIS_HOST__'", $redisHost `
    -replace "'__REDIS_PORT__'", $redisPort
  [System.IO.File]::WriteAllText($wrapperScript, $wrapperContent, [System.Text.UTF8Encoding]::new($false))

  # check-suppress:suppression_doc: probe whether service already exists; Get-Service throws when absent.
  $existingService = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
  if ($null -eq $existingService) {
    Set-NucleusService -Name $serviceName -BinaryPath "pwsh.exe -NoLogo -ExecutionPolicy Bypass -File `"$wrapperScript`"" -DisplayName "nucleus LiteLLM AI gateway proxy" -Description "Managed LiteLLM proxy for unified AI model access (http://$($litellmEndpoint.host):$($litellmEndpoint.port))"
    Write-NucleusInfo -CommandName 'litellm' "created SCM service '$serviceName'"
  }
  else {
    Set-NucleusService -Name $serviceName -BinaryPath "pwsh.exe -NoLogo -ExecutionPolicy Bypass -File `"$wrapperScript`"" -DisplayName "nucleus LiteLLM AI gateway proxy" -Description "Managed LiteLLM proxy for unified AI model access (http://$($litellmEndpoint.host):$($litellmEndpoint.port))"
    Write-NucleusInfo -CommandName 'litellm' "updated SCM service '$serviceName'"
  }

  Write-NucleusInfo -CommandName 'litellm' 'ensured SCM service on http://127.0.0.1:4000'
}
