# Generated by nucleus-vm setup — start-__VM_NAME__.ps1. Dispatches to the
# hypervisor selected by __HOST_KIND__ (Tart, UTM, or libvirt), substituted at
# VM creation time. Other placeholders (VM_NAME, VM_DISPLAY, VM_DIR) are
# similarly substituted.

$vmName = '__VM_NAME__'
$vmDisplay = '__VM_DISPLAY__'
$vmDir = '__VM_DIR__'

switch ('__HOST_KIND__') {
  'darwin-tart' {
    & tart run $vmName
  }
  'darwin-utm' {
    if (Test-Path '/Applications/UTM.app/Contents/MacOS/utmctl') {
      & '/Applications/UTM.app/Contents/MacOS/utmctl' start $vmDisplay
      if ($LASTEXITCODE -ne 0) {
        Write-Warning "nucleus-vm: utmctl start failed for $vmName; opening bundle instead"
        Start-Process -FilePath open -ArgumentList "$vmDir/$vmName.utm" > $null
      }
    } else {
      Start-Process -FilePath open -ArgumentList "$vmDir/$vmName.utm" > $null
    }
  }
  'nixos-libvirt' {
    & virsh start $vmName > $null
    if ($LASTEXITCODE -ne 0) {
      Write-Warning "nucleus-vm: virsh start failed (or VM already running): $vmName"
    }
    if (Get-Command virt-viewer -ErrorAction SilentlyContinue) {  # check-suppress:suppression_doc: virt-viewer optional; absent falls back to console hint
      & virt-viewer --connect qemu:///system $vmName
    } else {
      Write-Output "nucleus-vm: VM started: $vmName"
      Write-Output 'nucleus-vm: install virt-viewer to open a console automatically'
    }
  }
  default {
    Write-Error "nucleus-vm: unknown host kind: __HOST_KIND__"
    exit 1
  }
}
