#!/usr/bin/env sh
# start-{{VM_NAME}}.sh — Start the '{{VM_DISPLAY}}' virtual machine.
# Generated by nucleus-vm-setup; re-run nucleus-vm-setup to regenerate.
set -eu

VM_DIR="{{VM_DIR}}"

case "{{HOST_KIND}}" in
  darwin-tart)
    exec tart run "{{VM_NAME}}"
    ;;
  darwin-utm)
    if command -v utmctl >/dev/null 2>&1; then
      utmctl start "{{VM_DISPLAY}}"
    else
      open "$VM_DIR/{{VM_NAME}}.utm"
    fi
    ;;
  nixos-libvirt)
    if ! virsh start "{{VM_NAME}}" >/dev/null; then
      printf 'vm-setup: virsh start failed (or VM already running): %s\n' "{{VM_NAME}}" >&2
    fi
    if command -v virt-viewer >/dev/null 2>&1; then
      exec virt-viewer --connect qemu:///system "{{VM_NAME}}"
    fi
    printf 'vm-setup: VM started: %s\n' "{{VM_NAME}}"
    printf 'vm-setup: install virt-viewer to open a console automatically\n'
    ;;
  *)
    printf 'vm-setup: unknown host kind: {{HOST_KIND}}\n' >&2
    exit 1
    ;;
esac
