#!/bin/sh
# start-<VM_NAME>.sh — Start the '<VM_DISPLAY>' QEMU virtual machine.
# Generated by Invoke-VMSetup; re-run nucleus-vm setup to regenerate.
# Windows-specific QEMU variant (Git Bash/MSYS). start-posix.sh is the
# cross-host dispatcher with different semantics — separate template per
# embedded-content policy §3.

set -eu

# SSH port forwarding (hostfwd) exposes host:2222 → guest:22 for SSH-based provisioning.
# QEMU GA (chardev pipe + virtio-serial) enables guest-agent commands via named pipe.

# shellcheck disable=SC1001 # reason: Windows named-pipe path must keep backslashes verbatim (unquoted per original; sh would otherwise consume them)
'__QEMU_SYSTEM__' \
    -name '__VM_DISPLAY__' \
    -machine __MACHINE__ \
    -cpu __CPU__ \
    -smp __CPUS__ \
    -m __RAM_MIB__ \
    -drive file='__DISK_PATH__',format=qcow2,if=virtio \
    -netdev user,id=net0,hostfwd=tcp::2222-:22 \
    -device virtio-net-pci,netdev=net0 \
    -vga __VGA__ \
    -display __DISPLAY_BACKEND__ \
    -rtc base=localtime \
    -chardev pipe,id=qga,path=\\.\pipe\qga-__VM_NAME__ \
    -device virtio-serial \
    -device virtserialport,chardev=qga,name=org.qemu.guest_agent.0 \
    -usb -device usb-tablet
