<#
.SYNOPSIS
    Start the '__VM_DISPLAY__' QEMU virtual machine.
.DESCRIPTION
    Generated by nucleus-vm setup; re-run nucleus-vm setup to regenerate.
    Invokes QEMU with the correct machine type, CPU, memory, disk, and
    network configuration. SSH port forwarding (hostfwd) comes from
    the VMs.json portForwards of this VM (injected via the HOSTFWDS
    token). QEMU GA (chardev pipe + virtio-serial) enables
    guest-agent commands via named pipe.
.NOTES
    Source: https://www.qemu.org/docs/master/system/invocation.html
    Environment variables: (none)
    Exit codes: 0 on success; non-zero on failure
    Placeholders (VM_NAME, VM_DISPLAY, MACHINE, CPU, CPUS, RAM_BYTES, DISK_PATH,
    VGA, DISPLAY_BACKEND, QEMU_SYSTEM, VIRTIOFS_ARGS, HOSTFWDS) are substituted by
    Invoke-VMSetup at generation time.
#>

__VIRTIOFS_ARGS__
& '__QEMU_SYSTEM__' `
    -name '__VM_DISPLAY__' `
    -machine __MACHINE__ `
    -cpu __CPU__ `
    -smp __CPUS__ `
    -m __RAM_BYTES__B `
    -drive file='__DISK_PATH__',format=qcow2,if=virtio `
    -netdev user,id=net0,__HOSTFWDS__ `
    -device virtio-net-pci,netdev=net0 `
    -vga __VGA__ `
    -display __DISPLAY_BACKEND__ `
    -rtc base=localtime `
    -chardev pipe,id=qga,path=\.\pipe\qga-__VM_NAME__ `
    -device virtio-serial `
    -device virtserialport,chardev=qga,name=org.qemu.guest_agent.0 `
    -usb -device usb-tablet
