#!/usr/bin/env bash
# start-<VM_NAME>.sh — Start the '<VM_DISPLAY>' QEMU virtual machine.
# Generated by Invoke-VMSetup; re-run nucleus-vm setup to regenerate.
# Placeholders (VM_NAME, VM_DISPLAY, MACHINE, CPU, CPUS, RAM_BYTES, DISK_PATH,
# VGA, DISPLAY_BACKEND, QEMU_SYSTEM, HOSTFWDS) are substituted by Invoke-VMSetup at
# generation time.
# Windows-specific QEMU variant (Git Bash/MSYS). start-posix.sh is the
# cross-host dispatcher with different semantics — separate template per
# embedded-content policy §3.

set -euo pipefail

# SSH port forwarding (hostfwd) comes from the VMs.json portForwards of this VM
# (injected via the HOSTFWDS token). QEMU GA (chardev pipe + virtio-serial) enables
# guest-agent commands via named pipe.

# The disk path below is relative to the VM tree root (data/<id>.qcow2) so the
# rendered script stays relocatable across hosts; run QEMU from the tree root
# so the relative path resolves from any working directory.
cd "$(dirname "$0")/.." || exit 1

# shellcheck disable=SC1001 # reason: Windows named-pipe path must keep backslashes verbatim (unquoted per original; bash would otherwise consume them)
'__QEMU_SYSTEM__' \
    -name '__VM_DISPLAY__' \
    -machine __MACHINE__ \
    -cpu __CPU__ \
    -smp __CPUS__ \
    -m __RAM_BYTES__B \
    -drive file='__DISK_PATH__',format=qcow2,if=virtio \
    -netdev user,id=net0,__HOSTFWDS__ \
    -device virtio-net-pci,netdev=net0 \
    -vga __VGA__ \
    -display __DISPLAY_BACKEND__ \
    -rtc base=localtime \
    -chardev pipe,id=qga,path=\\.\pipe\qga-__VM_ID__ \
    -device virtio-serial \
    -device virtserialport,chardev=qga,name=org.qemu.guest_agent.0 \
    -usb -device usb-tablet
