#!/usr/bin/env sh
# start-{{VM_NAME}}.sh — Start the '{{VM_DISPLAY}}' virtual machine.
#
# This script is generated by nucleus-vm-setup. To regenerate, re-run
# nucleus-vm-setup. It dispatches to the appropriate hypervisor (Tart, UTM, or
# libvirt/virt-viewer) based on the {{HOST_KIND}} variable.
#
# Template file: placeholders like {{VM_NAME}} are substituted at VM creation time.
#
# Arguments:
#   (none)        No arguments accepted.
#
# Environment variables:
#   (none)        No environment variables used.
#
# Exit conditions:
#   0 on success; non-zero if HOST_KIND is unrecognized.
set -eu

VM_DIR="{{VM_DIR}}"

# shellcheck disable=SC2194
case "{{HOST_KIND}}" in
  darwin-tart)
    exec tart run "{{VM_NAME}}"
    ;;
  darwin-utm)
    if command -v utmctl >/dev/null 2>&1; then
      utmctl start "{{VM_DISPLAY}}"
    else
      open "$VM_DIR/{{VM_NAME}}.utm"
    fi
    ;;
  nixos-libvirt)
    if ! virsh start "{{VM_NAME}}" >/dev/null; then
      printf 'vm-setup: virsh start failed (or VM already running): %s\n' "{{VM_NAME}}" >&2
    fi
    if command -v virt-viewer >/dev/null 2>&1; then
      exec virt-viewer --connect qemu:///system "{{VM_NAME}}"
    fi
    printf 'vm-setup: VM started: %s\n' "{{VM_NAME}}"
    printf 'vm-setup: install virt-viewer to open a console automatically\n'
    ;;
  *)
    printf 'vm-setup: unknown host kind: {{HOST_KIND}}\n' >&2
    exit 1
    ;;
esac
