<#
.SYNOPSIS
    Start the '{{VM_DISPLAY}}' QEMU virtual machine.
.DESCRIPTION
    Generated by nucleus-vm setup; re-run nucleus-vm setup to regenerate.
    Invokes QEMU with the correct machine type, CPU, memory, disk, and
    network configuration. SSH port forwarding (hostfwd) exposes
    host:2222 → guest:22 for SSH-based provisioning. QEMU GA
    (chardev pipe + virtio-serial) enables guest-agent commands via
    named pipe.
.NOTES
    Source: https://www.qemu.org/docs/master/system/invocation.html
    Environment variables: (none)
    Exit codes: 0 on success; non-zero on failure
#>

{{VIRTIOFS_ARGS}}
& '{{QEMU_SYSTEM}}' `
    -name '{{VM_DISPLAY}}' `
    -machine {{MACHINE}} `
    -cpu {{CPU}} `
    -smp {{CPUS}} `
    -m {{RAM_MIB}} `
    -drive file='{{DISK_PATH}}',format=qcow2,if=virtio `
    -netdev user,id=net0,hostfwd=tcp::2222-:22 `
    -device virtio-net-pci,netdev=net0 `
    -vga {{VGA}} `
    -display {{DISPLAY_BACKEND}} `
    -rtc base=localtime `
    -chardev pipe,id=qga,path=\\.\pipe\qga-{{VM_NAME}} `
    -device virtio-serial `
    -device virtserialport,chardev=qga,name=org.qemu.guest_agent.0 `
    -usb -device usb-tablet
