#!/bin/sh
# Generated by nucleus-vm setup — stop-<VM_NAME>.sh. Dispatches to the
# hypervisor selected by <HOST_KIND> (Tart, UTM, or libvirt), substituted at
# VM creation time. Other placeholders (VM_NAME, VM_DISPLAY) are similarly
# substituted.

set -eu

HOST_KIND="__HOST_KIND__"
case "$HOST_KIND" in
  darwin-tart)
    exec tart stop "__VM_NAME__"
    ;;
  darwin-utm)
    if command -v utmctl >/dev/null 2>&1; then
      exec utmctl stop "__VM_DISPLAY__"
    fi
    echo "utmctl not found; VM may still be running" >&2
    exit 1
    ;;
  nixos-libvirt)
    if virsh shutdown "__VM_NAME__" 2>/dev/null; then
      echo "ACPI shutdown signal sent to __VM_NAME__"
    else
      echo "virsh shutdown failed; trying virsh destroy..." >&2
      exec virsh destroy "__VM_NAME__"
    fi
    ;;
  *)
    echo "nucleus-vm: unknown host kind: __HOST_KIND__" >&2
    exit 1
    ;;
esac
