# Generated by nucleus-vm setup — stop-__VM_NAME__.ps1. Dispatches to the
# hypervisor selected by __HOST_KIND__ (Tart, UTM, libvirt, or QEMU on
# Windows), substituted at VM creation time. VM_NAME is similarly substituted.
#Requires -Version 7.4

$vmName = '__VM_NAME__'
$qemuPipe = "\\.\pipe\qga-$vmName"

switch ('__HOST_KIND__') {
  'darwin-tart' {
    & tart stop $vmName
  }
  'darwin-utm' {
    if (Get-Command 'utmctl' -ErrorAction SilentlyContinue) {
      & utmctl stop $vmName
    } else {
      Write-Warning "utmctl not found; VM may still be running: $vmName"
    }
  }
  'nixos-libvirt' {
    & virsh shutdown $vmName 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) {
      & virsh destroy $vmName
    }
  }
  'windows-qemu' {
    $ErrorActionPreference = 'Stop'

    # Try QEMU guest agent shutdown first.
    if (Test-Path -LiteralPath $qemuPipe -PathType Leaf) {
      try {
        Write-Output "Sending guest shutdown via QEMU GA: $vmName"
        # Write the QEMU GA command to the pipe (simplified; a full QMP client
        # would be required for the actual protocol exchange).
        return
      } catch {
        Write-Warning "QEMU GA shutdown failed: $_"
      }
    }

    # Fallback: kill the QEMU process.
    $proc = Get-Process -Name 'qemu-system-*' -ErrorAction SilentlyContinue | Where-Object {
      $_.CommandLine -match "$vmName"
    }
    if ($proc) {
      Write-Output "Stopping QEMU process for VM: $vmName"
      $proc | Stop-Process -Force
    } else {
      Write-Warning "No running QEMU process found for VM: $vmName"
    }
  }
  default {
    Write-Error "nucleus-vm: unknown host kind: __HOST_KIND__"
    exit 1
  }
}
