#!/usr/bin/env bash
# Generated by nucleus-vm setup — stop-<VM_NAME>.sh. Dispatches to the
# hypervisor selected by <HOST_KIND> (Tart, UTM, or libvirt), substituted at
# VM creation time. Other placeholders (VM_NAME, VM_DISPLAY) are similarly
# substituted.
#
# NOTE: lib.sh output helpers are not available here — vm.sh renders this
# template via sed token substitution into a standalone guest script — so
# output uses the literal "vm-setup:" prefix.

set -euo pipefail

HOST_KIND="__HOST_KIND__"
case "$HOST_KIND" in
darwin-tart)
  exec tart stop "__VM_ID__"
  ;;
darwin-utm)
  if command -v utmctl >/dev/null 2>&1; then
    exec utmctl stop "__VM_DISPLAY__"
  fi
  echo "vm-setup: utmctl not found; VM may still be running" >&2
  exit 1
  ;;
nixos-libvirt)
  if virsh shutdown "__VM_ID__" 2>/dev/null; then
    echo "vm-setup: ACPI shutdown signal sent to __VM_ID__"
  else
    echo "vm-setup: virsh shutdown failed; trying virsh destroy..." >&2
    exec virsh destroy "__VM_ID__"
  fi
  ;;
*)
  echo "vm-setup: unknown host kind: __HOST_KIND__" >&2
  exit 1
  ;;
esac
