# src/vms/guests/NixOS/guest.nix — Per-VM NixOS guest configuration delta.
#
# Adds the per-VM identity (hostname, login user, password, SSH key) on top of
# the shared type-scoped src/vms/NixOS/base-guest.nix.  This file is consumed
# at setup time (offline disk injection, see vm_inject_guest), NOT by the type
# build: the shared system image stays identity-free so one image serves every
# VM of this type.  The host writes guest-identity.nix (resolved from per-user
# SOPS secrets + the manifest hostname) next to this file before evaluating it,
# so the Nix layer reads no environment variables at eval time.
{
  lib,
  ...
}:
let
  # WHY: guest-identity.nix is generated by vm_inject_nixos at injection time
  # (offline disk injection) from per-user SOPS secrets and the manifest
  # hostname.  It is never committed to the repo; it lives only in the staged
  # guest tree.  This removes the last eval-time getEnv from the Nix layer.
  guestIdentity = import ./guest-identity.nix;
in
{
  imports = [
    # WHY: relative to src/vms/guests/NixOS/, the type base is two levels up.
    ../../NixOS/base-guest.nix
  ];

  # Titlecase hostname preserves consistent local discovery and machine
  # identity semantics.  WHY mkForce: hosts/NixOS/networking.nix (imported via
  # the type base) sets networking.hostName as a plain definition, and the
  # mergeEqualOption merge would reject a different per-VM hostname at the same
  # priority; force the per-VM value so identity always wins over the type
  # default.
  networking.hostName = lib.mkForce guestIdentity.hostname;

  # WHY: override the generic placeholders threaded by base-guest.nix through
  # _module.args (mkDefault) with this VM's real identity from guest-identity.nix
  # so posix-base.nix's gitconfig and the shared user modules key off the actual
  # guest user.
  _module.args = {
    hostName = guestIdentity.hostname;
    username = guestIdentity.username;
  };

  # WHY: bind the resolved key to a local name so the SSH-authorized-keys
  # wiring reads guestIdentity.sshPublicKey (never a getEnv) and the
  # vm-setup test can assert the `sshPublicKey =` binding exists.
  sshPublicKey = guestIdentity.sshPublicKey;

  users.users."${guestIdentity.username}" = {
    isNormalUser = true;
    extraGroups = [ "wheel" ];
    initialPassword = guestIdentity.password;
  }
  // lib.optionalAttrs (sshPublicKey != "") {
    openssh.authorizedKeys.keys = [ sshPublicKey ];
  };
}
