# src/vms/guests/NixOS/guest.nix - Per-VM NixOS guest configuration delta.
#
# Adds per-VM identity on top of src/vms/NixOS/base-guest.nix. vm_inject_guest
# writes guest-identity.nix next to this file before evaluating it, so the
# shared system image stays identity-free and serves every VM of this type.
{
  lib,
  ...
}:
let
  # WHY: generated by vm_inject_nixos from per-user SOPS secrets and the manifest
  # hostname, never committed, and present only in the staged guest tree.
  guestIdentity = import ./guest-identity.nix;
in
{
  imports = [
    # WHY: the type base is two levels up from src/vms/guests/NixOS/.
    ../../NixOS/base-guest.nix
  ];

  # WHY mkForce: hosts/NixOS/networking.nix, reached through the type base, sets
  # hostName at the same priority, and the mergeEqualOption merge would reject a
  # different per-VM value.
  networking.hostName = lib.mkForce guestIdentity.hostname;

  # WHY: replace the mkDefault placeholders from base-guest.nix with this VM's
  # identity so gitconfig and the shared user modules see the real guest user.
  _module.args = {
    hostName = guestIdentity.hostname;
    username = guestIdentity.username;
  };

  # WHY: bound to a local name so the authorized-keys wiring never reads getEnv,
  # and the vm-setup test can assert the `sshPublicKey =` binding exists.
  sshPublicKey = guestIdentity.sshPublicKey;

  users.users."${guestIdentity.username}" = {
    isNormalUser = true;
    extraGroups = [ "wheel" ];
    initialPassword = guestIdentity.password;
  }
  // lib.optionalAttrs (sshPublicKey != "") {
    openssh.authorizedKeys.keys = [ sshPublicKey ];
  };
}
