#!/usr/bin/env bash
# Clears Finder's saved application state cache so that desktop visibility
# settings (ShowExternalHardDrivesOnDesktop, ShowHardDrivesOnDesktop,
# ShowMountedServersOnDesktop, ShowRemovableMediaOnDesktop) take effect
# immediately. Without this, Finder may display a stale cached state even
# when system.defaults has been correctly updated. The cache file is
# automatically regenerated by Finder on next launch with current defaults.
#
# WHY: Finder's cached state can become stale or corrupted, causing it to
# ignore system default changes. Clearing it on every apply ensures the
# live system state matches declared configuration without requiring manual
# user intervention (Cmd+Opt+Esc, cache deletion, etc.).

SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"
# shellcheck source=../../../scripts/lib/macos-console-user.sh
. "$SCRIPT_DIR/../../../scripts/lib/macos-console-user.sh"
# shellcheck source=../../../scripts/lib/lib.sh
. "$SCRIPT_DIR/../../../scripts/lib/lib.sh"

if _nucleus_resolve_console_user; then
  finder_cache_dir="/Users/$_nucleus_console_user/Library/Saved Application State/com.apple.finder.savedState"
  if [ -d "$finder_cache_dir" ]; then
    if /bin/rm -rf "$finder_cache_dir"; then
      say -l finder "cleared cached application state from $finder_cache_dir"
    else
      # check-suppress:suppression_doc: cache clear is best-effort; missing cache is not a config failure
      warn -l finder "failed to clear cached state at $finder_cache_dir (user may need manual restart)."
    fi
  fi
  # Process restarts handled by Home Manager's relaunchDesktopServices step.
fi
