#!/usr/bin/env sh
# Provisions and configures virtual machines declared in src/modules/VMs.json.
#
# What it does:
#   macOS  (Darwin): copies Nix-generated UTM config.plist templates into
#                    ~/virtual machines/<name>.utm bundles and pre-allocates
#                    QCOW2 disk images.
#   NixOS  (Linux/NIXOS): passes Nix-generated domain XML files to virsh define
#                    so KVM-accelerated VMs are ready for use.
#   Other Linux:     prints instructions for manual QEMU setup.
#
# Disk format: QCOW2 throughout (UTM, libvirt/QEMU, and Windows QEMU all speak
# QCOW2 natively), enabling copy-based migration between all three platforms.
#
# Arguments:
#   --dry-run  print planned actions without executing them
#
# Environment variables:
#   VM_DIR_OVERRIDE  override the default ~/virtual machines path
#
# Prerequisites:
#   macOS:  UTM installed (/Applications/UTM.app); qemu-img in PATH for
#           disk pre-allocation (falls back to sparse raw file if absent).
#           Nix-generated plists at ~/.local/share/nucleus/vms/ (run apply first).
#   NixOS:  virsh in PATH (provided by the libvirt package in VMs.nix);
#           qemu-img in PATH (provided by qemu in VMs.nix);
#           domain XML at /etc/nucleus/vms/ (generated by VMs.nix at apply time).
#
# Exit: always 0 (best-effort — a VM setup failure does not roll back a
#       completed system apply).

set -eu

SCRIPT_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH='' cd -- "$SCRIPT_DIR/.." && pwd)
MANIFEST="$REPO_ROOT/src/modules/VMs.json"

dry_run=false

while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run)
      dry_run=true
      ;;
    *)
      printf 'VM-setup: unsupported argument "%s"\n' "$1" >&2
      exit 1
      ;;
  esac
  shift
done

if [ ! -f "$MANIFEST" ]; then
  printf 'VM-setup: manifest not found at %s; skipping\n' "$MANIFEST" >&2
  exit 0
fi

if ! command -v jq >/dev/null 2>&1; then
  printf 'VM-setup: jq not found in PATH; cannot parse manifest\n' >&2
  exit 0
fi

VM_DIR="${VM_DIR_OVERRIDE:-$HOME/virtual machines}"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

run_cmd() {
  if [ "$dry_run" = true ]; then
    printf 'VM-setup: [dry-run] %s\n' "$*"
  else
    "$@"
  fi
}

create_qcow2_disk() {
  _disk_path="$1"
  _disk_gib="$2"
  if [ -f "$_disk_path" ]; then
    printf 'VM-setup: disk already exists: %s\n' "$_disk_path"
    return
  fi
  if command -v qemu-img >/dev/null 2>&1; then
    printf 'VM-setup: creating QCOW2 disk (%s GiB): %s\n' "$_disk_gib" "$_disk_path"
    run_cmd qemu-img create -f qcow2 "$_disk_path" "${_disk_gib}G"
  else
    # Fallback: create a sparse raw disk image.  On macOS this produces a
    # sparse file via HFS+/APFS copy-on-write; on Linux via ext4 sparse blocks.
    # The guest can use this as a raw disk; convert to QCOW2 later with
    # `qemu-img convert -f raw -O qcow2 <raw> <qcow2>`.
    printf 'VM-setup: qemu-img not found; creating sparse raw disk (%s GiB): %s\n' "$_disk_gib" "$_disk_path"
    run_cmd dd if=/dev/zero bs=1 count=0 seek=$((_disk_gib * 1073741824)) of="$_disk_path" 2>/dev/null || true
  fi
}

write_configure_script() {
  # Generate a reference script documenting how to apply the nucleus host
  # configuration inside the named VM guest.
  _wcs_name="$1"
  _wcs_type="$2"
  _wcs_script="$VM_DIR/${_wcs_name}-configure.sh"
  case "$_wcs_type" in
    nixos)
      cat > "$_wcs_script" << 'CFGEOF'
#!/usr/bin/env sh
# Apply the nucleus nixos host configuration inside this VM.
# ~/dev is shared via VirtioFS when shareDevDir=true.
sudo nixos-rebuild switch --flake "$HOME/dev/nucleus/src#nixos"
CFGEOF
      ;;
    windows)
      cat > "$_wcs_script" << 'CFGEOF'
#!/usr/bin/env sh
# Apply the nucleus Windows host configuration inside this VM.
# Clone this repository to %USERPROFILE%\dev\nucleus inside the VM, then run:
#   .\src\hosts\windows\apply.ps1
CFGEOF
      ;;
    macos)
      cat > "$_wcs_script" << 'CFGEOF'
#!/usr/bin/env sh
# Apply the nucleus macbook host configuration inside this VM.
# Clone this repository to ~/dev/nucleus inside the VM, then run:
#   ~/dev/nucleus/scripts/bootstrap.sh apply
CFGEOF
      ;;
    *)
      return
      ;;
  esac
  chmod +x "$_wcs_script"
  printf 'VM-setup: wrote configure script: %s\n' "$_wcs_script"
}

# ---------------------------------------------------------------------------
# macOS / UTM
# ---------------------------------------------------------------------------

setup_utm_vms() {
  UTMCTL="/Applications/UTM.app/Contents/MacOS/utmctl"

  if [ ! -d /Applications/UTM.app ]; then
    printf 'VM-setup: UTM not found at /Applications/UTM.app; skipping macOS VM provisioning\n'
    return
  fi

  if [ ! -x "$UTMCTL" ]; then
    printf 'VM-setup: utmctl not found at %s; skipping macOS VM provisioning\n' "$UTMCTL"
    return
  fi

  vm_count=$(jq '.vms | length' "$MANIFEST")
  i=0
  while [ "$i" -lt "$vm_count" ]; do
    vm_name=$(jq -r ".vms[$i].name" "$MANIFEST")
    vm_display=$(jq -r ".vms[$i].display" "$MANIFEST")
    vm_disk=$(jq -r ".vms[$i].diskGiB" "$MANIFEST")
    vm_type=$(jq -r ".vms[$i].type" "$MANIFEST")

    bundle="$VM_DIR/${vm_name}.utm"
    images_dir="$bundle/Images"
    disk_file="$images_dir/disk-main.qcow2"
    config_plist="$bundle/config.plist"

    printf 'VM-setup: configuring UTM VM "%s"...\n' "$vm_display"

    # Check if bundle already exists to avoid overwriting.
    if [ -d "$bundle" ]; then
      printf 'VM-setup: UTM bundle already exists: %s; skipping\n' "$bundle"
      i=$((i + 1))
      continue
    fi

    # Use the Nix-generated UTM config.plist written to ~/.local/share/nucleus/
    # at Home Manager activation time (run nucleus-apply first).
    _plist_template="${HOME}/.local/share/nucleus/vms/${vm_name}-config.plist"
    if [ ! -f "$_plist_template" ]; then
      printf 'VM-setup: WARNING \u2014 UTM config template not found at %s; apply the macOS config first\n' "$_plist_template" >&2
      i=$((i + 1))
      continue
    fi

    if [ "$dry_run" = false ]; then
      mkdir -p "$images_dir"
      create_qcow2_disk "$disk_file" "$vm_disk"
      cp "$_plist_template" "$config_plist"
      printf 'VM-setup: UTM bundle created: %s\n' "$bundle"
      # Register with UTM by opening the bundle package.
      open "$bundle"
      write_configure_script "$vm_name" "$vm_type"
      printf 'VM-setup: attach an installation ISO in UTM to install the "%s" guest OS\n' "$vm_display"
    else
      printf 'VM-setup: [dry-run] create UTM bundle %s from %s\n' "$bundle" "$_plist_template"
    fi

    i=$((i + 1))
  done

  printf 'VM-setup: macOS VM setup complete\n'
}

# ---------------------------------------------------------------------------
# NixOS / libvirt
# ---------------------------------------------------------------------------

setup_libvirt_vms() {
  if ! command -v virsh >/dev/null 2>&1; then
    printf 'VM-setup: virsh not found in PATH; libvirtd may not be enabled yet\n'
    printf 'VM-setup: apply the NixOS configuration first so VMs.nix activates libvirtd\n'
    return
  fi

  # Ensure the libvirt default network is started so VMs can reach the host.
  if virsh net-list --all 2>/dev/null | grep -q "default"; then
    if ! virsh net-list 2>/dev/null | grep -q "default.*active"; then
      printf 'VM-setup: starting libvirt default network...\n'
      run_cmd virsh net-start default || true
      run_cmd virsh net-autostart default || true
    fi
  fi

  vm_count=$(jq '.vms | length' "$MANIFEST")
  i=0
  while [ "$i" -lt "$vm_count" ]; do
    vm_name=$(jq -r ".vms[$i].name" "$MANIFEST")
    vm_display=$(jq -r ".vms[$i].display" "$MANIFEST")
    vm_disk=$(jq -r ".vms[$i].diskGiB" "$MANIFEST")
    vm_type=$(jq -r ".vms[$i].type" "$MANIFEST")

    disk_path="$VM_DIR/${vm_name}.qcow2"

    printf 'VM-setup: configuring libvirt VM "%s"...\n' "$vm_display"

    if [ "$dry_run" = false ]; then
      mkdir -p "$VM_DIR"
      create_qcow2_disk "$disk_path" "$vm_disk"
    else
      printf 'VM-setup: [dry-run] create disk %s (%s GiB)\n' "$disk_path" "$vm_disk"
    fi

    # Define/update the libvirt domain from the Nix-generated XML (idempotent).
    # The file is installed at apply time by environment.etc in VMs.nix.
    _xml_file="/etc/nucleus/vms/${vm_name}-domain.xml"
    if [ ! -f "$_xml_file" ]; then
      printf 'VM-setup: WARNING — domain XML not found at %s; apply the NixOS config first\n' "$_xml_file" >&2
      i=$((i + 1))
      continue
    fi

    if [ "$dry_run" = false ]; then
      if virsh define "$_xml_file"; then
        printf 'VM-setup: VM "%s" defined/updated in libvirt\n' "$vm_name"
        write_configure_script "$vm_name" "$vm_type"
        printf 'VM-setup: install a guest OS via: virt-manager or virsh console %s\n' "$vm_name"
      else
        printf 'VM-setup: WARNING — virsh define failed for "%s"; check libvirtd status\n' "$vm_name" >&2
      fi
    else
      printf 'VM-setup: [dry-run] virsh define %s\n' "$_xml_file"
    fi

    i=$((i + 1))
  done

  printf 'VM-setup: NixOS VM setup complete; use virt-manager to install guest OSes\n'
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

printf 'VM-setup: reading manifest from %s\n' "$MANIFEST"
if [ "$dry_run" = true ]; then
  printf 'VM-setup: dry-run mode — no changes will be made\n'
fi

if [ "$dry_run" = false ]; then
  mkdir -p "$VM_DIR"
fi

_os=$(uname -s)
case "$_os" in
  Darwin)
    setup_utm_vms
    ;;
  Linux)
    if [ -f /etc/NIXOS ]; then
      setup_libvirt_vms
    else
      printf 'VM-setup: standalone Linux detected; use QEMU/KVM directly:\n'
      printf 'VM-setup:   qemu-img create -f qcow2 ~/virtual\ machines/<name>.qcow2 <size>G\n'
      printf 'VM-setup:   qemu-system-x86_64 -m <ram> -smp <cpu> -hda ~/virtual\ machines/<name>.qcow2 ...\n'
    fi
    ;;
  *)
    printf 'VM-setup: unsupported OS "%s"; nothing to do\n' "$_os"
    ;;
esac

printf 'VM-setup: done\n'
