#!/usr/bin/env bash
# Write the deployed method-1 symlink manifest consumed by check step 19.
#
# The manifest is the deployed source of truth for "which paths must resolve into
# the LIVE repo root": it is generated from the same Nix value that feeds the
# unprotect/protect activations (managedSymlinkPaths) plus the agent, cursor and
# editor overlay roots. Step 19's previous hand-maintained candidate list had
# already drifted from the deployed set, which is the failure this file removes.
#
# Directory entries are walked one level by the step; file entries are inspected
# directly.
#
# Usage: write-method1-symlink-manifest <manifest-path> <paths-json> <jq-bin>
#   <manifest-path>  absolute path to write; parent directories are created
#   <paths-json>     JSON array of absolute path strings, in a stable order
#   <jq-bin>         store path of jq
# Exit: 0 on success; non-zero when an entry is not an absolute path — a relative
#       entry would make the step's walk depend on the caller's working
#       directory, so it is refused rather than written.
set -euo pipefail

SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"
# shellcheck source=../lib/lib.sh
. "$SCRIPT_DIR/../lib/lib.sh"

_manifest="$1"
_paths_json="$2"
_jq_bin="$3"

# Validate every entry before writing anything.
while IFS= read -r _m1_entry; do
  case "$_m1_entry" in
  /*) ;;
  *) die -l method1-manifest "manifest entry '$_m1_entry' is not an absolute path" ;;
  esac
done < <(printf '%s' "$_paths_json" | "$_jq_bin" -r '.[]')

mkdir -p "$(dirname "$_manifest")"
# Write beside the target and move into place so a reader never sees a partial
# manifest, and so the final rename cannot cross a filesystem boundary.
_m1_tmp="$_manifest.tmp.$$"
trap 'rm -f "$_m1_tmp"' EXIT

{
  printf '# Deployed method-1 symlink manifest — generated by write-method1-symlink-manifest.sh.\n'
  printf '# Rewritten on every nucleus-apply; read by check step 19. Do not edit by hand.\n'
  printf '%s' "$_paths_json" | "$_jq_bin" -r '.[]'
} >"$_m1_tmp"

mv "$_m1_tmp" "$_manifest"
trap - EXIT
