discord:
  status_type: song
  show_progress: true
  show_source_logo: true
  show_urls: true
  show_ad: true
spotify:
  enabled: false
  client_id: null
  client_secret: null
  redirect_uri: http://localhost:8888/callback
lastfm:
  enabled: true
  username: null
  api_key: null
plex:
  enabled: true
  server_url: null
  token: null
  libraries: []
soundcloud:
  enabled: true
youtube:
  enabled: true
