# MacBook/sops.nix — MacBook-specific SOPS overrides.
# Shared POSIX SOPS defaults live in ../../modules/posix-sops.nix.
{ username, ... }:
let
  # Data-driven: read keys-manifest.json to determine which SOPS secrets
  # to declare.  The manifest is generated by apply.sh before nixos-rebuild.
  manifest = builtins.fromJSON (builtins.readFile ../../modules/ai/keys-manifest.json);
  availableKeys = manifest.availableKeys or [ ];
in
{
  # System-level SOPS secrets used by the system-wide LiteLLM launchd daemon
  # (hosts/MacBook/ai.nix).  sops-nix writes each secret as a plain file to
  # /run/secrets/<name> by default.
  # OWNER: the launchd daemon runs as `username` (not root), so the secret
  # files must be owned by and readable by that user.
  sops.secrets = builtins.listToAttrs (
    map (keyName: {
      name = keyName;
      value = {
        sopsFile = ../../secrets/system.yml;
        owner = username;
        mode = "0400";
      };
    }) availableKeys
  );
}
