# NixOS/sops.nix — NixOS-specific SOPS overrides.
# Shared POSIX SOPS defaults live in ../../modules/posix-sops.nix.
#
# LiteLLM service runs as the dedicated `litellm` user (declared in
# hosts/NixOS/ai.nix), so the AI API key secrets must be owned by it.
{ ... }:
let
  # Data-driven: read keys-manifest.json to determine which SOPS secrets
  # to declare.  The manifest is generated by apply.sh before nixos-rebuild.
  manifest = builtins.fromJSON (builtins.readFile ../../modules/ai/keys-manifest.json);
  availableKeys = manifest.availableKeys or [ ];
in
{
  # System-level SOPS secrets used by the LiteLLM systemd service
  # (hosts/NixOS/ai.nix).  sops-nix writes each secret as a plain file to
  # /run/secrets/<name> by default.
  # OWNER: the systemd service runs as `litellm` (not root and not the user),
  # so the secret files must be owned by and readable by that user.
  sops.secrets = builtins.listToAttrs (
    map (keyName: {
      name = keyName;
      value = {
        sopsFile = ../../secrets/system.yml;
        owner = "litellm";
        mode = "0400";
      };
    }) availableKeys
  );
}
