#!/usr/bin/env bash
# Tests for src/scripts/completions/gen-completions.sh: --help contract, --check determinism,
# idempotent regeneration, 13-command coverage, generated headers + zsh syntax,
# update lockfile --list-* dynamic wiring, flag-extraction correctness pins, and
# spec-word escaping of shell metacharacters in subcommand descriptions.

set -euo pipefail

SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"
REPO_ROOT="$(CDPATH='' cd -- "$SCRIPT_DIR/../.." && pwd -P)"
# shellcheck source=./test-lib.sh
. "$SCRIPT_DIR/test-lib.sh"

cd "$REPO_ROOT"

_gen_script="src/scripts/completions/gen-completions.sh"
_COMPLETIONS_DIR="src/modules/completions/zsh"

# The canonical nucleus-* command set (alphabetical) — must match the generator.
# Subcommands are covered by their parent completion files, not as standalone
# commands: check packer/sh/pwsh, gc cleanup-nix/preferences, apply
# health-check/audit-store, cloud setup/reset/sync/repair, update lockfile.
_NUCLEUS_COMMANDS=(ai apply bootstrap check cloud config gc utils svc test update vm)

# 1. --help exits 0 and prints a usage: line.
if _help_out="$(bash "$_gen_script" --help 2>&1)" && printf '%s\n' "$_help_out" | grep -q '^usage: '; then
  assert_pass "gen-completions: --help exits 0 and prints usage line"
else
  assert_fail "gen-completions: --help contract" "exit code or usage line missing"
fi

# 2. Regenerate the tree, then --check must exit 0.
if bash "$_gen_script" >/dev/null 2>&1 && bash "$_gen_script" --check >/dev/null 2>&1; then
  assert_pass "gen-completions: generate then --check exits 0"
else
  assert_fail "gen-completions: generate + --check" "non-zero exit"
fi

# 3. Idempotency: a second generate is byte-identical (git-free comparison).
_tmp_snapshot="$(mktemp -d)"
_tmp_stub_repo="$(mktemp -d)"
trap 'rm -rf "$_tmp_snapshot" "$_tmp_stub_repo"' EXIT
cp -R "$_COMPLETIONS_DIR/." "$_tmp_snapshot/"
if bash "$_gen_script" >/dev/null 2>&1 && diff -rq "$_tmp_snapshot" "$_COMPLETIONS_DIR" >/dev/null 2>&1; then
  assert_pass "gen-completions: regeneration is idempotent"
else
  assert_fail "gen-completions: idempotency" "files changed after regenerate"
fi

# 4. Coverage: every command has a zsh completion file.
_coverage_ok=1
for _cmd in "${_NUCLEUS_COMMANDS[@]}"; do
  if [ ! -f "$_COMPLETIONS_DIR/_nucleus-$_cmd" ]; then
    assert_fail "gen-completions: coverage" "missing $_COMPLETIONS_DIR/_nucleus-$_cmd"
    _coverage_ok=0
  fi
done
if [ "$_coverage_ok" -eq 1 ]; then
  assert_pass "gen-completions: all ${#_NUCLEUS_COMMANDS[@]} commands have zsh completion files"
fi

# 5. Generated headers + zsh syntax (skipped when zsh is unavailable).
if command -v zsh >/dev/null 2>&1; then
  _gen_ok=1
  for _zsh_f in "$_COMPLETIONS_DIR"/_nucleus "$_COMPLETIONS_DIR"/_nucleus-*; do
    [ -f "$_zsh_f" ] || continue
    _name="$(basename "$_zsh_f")"
    if ! grep -q '^# GENERATED by src/scripts/completions/gen-completions.sh' "$_zsh_f"; then
      assert_fail "gen-completions: generated header" "$_name lacks GENERATED header"
      _gen_ok=0
    fi
    # check-suppress:suppression_doc: zsh -n stderr is not needed; the exit code decides the assertion.
    if ! zsh -n "$_zsh_f" 2>/dev/null; then
      assert_fail "gen-completions: zsh -n" "$_name syntax error"
      _gen_ok=0
    fi
  done
  if [ "$_gen_ok" -eq 1 ]; then
    assert_pass "gen-completions: all generated files have headers and pass zsh -n"
  fi
else
  assert_skip "gen-completions: zsh syntax check" "zsh not available"
fi

# 6. update lockfile dynamic value completion via --list-sections.
if grep -q "_call_program 'sections' nucleus-update --list-sections" "$_COMPLETIONS_DIR/_nucleus-update" &&
  grep -q -- '--sections:section name:->sections' "$_COMPLETIONS_DIR/_nucleus-update"; then
  assert_pass "gen-completions: update lockfile --sections dynamic wiring"
else
  assert_fail "gen-completions: update lockfile --sections wiring" "missing _call_program/->sections"
fi

# 8. Flag extraction correctness: usage-line + body flags land in the spec,
#    corrected sets are pinned (apply's 12 flags + health-check/audit-store
#    subcommands, test's -q group, optimize-pdf --rm-bak), and no jq/rclone/curl
#    tool flags leak into any file.
if [ "$(grep -cE "^  '--" "$_COMPLETIONS_DIR/_nucleus-apply")" -eq 12 ] &&
  grep -q -- "'--ai-sync\[ai sync\]'" "$_COMPLETIONS_DIR/_nucleus-apply" &&
  grep -q -- 'health-check' "$_COMPLETIONS_DIR/_nucleus-apply" &&
  grep -q -- 'audit-store' "$_COMPLETIONS_DIR/_nucleus-apply" &&
  grep -q -- "'-q\[q\]'" "$_COMPLETIONS_DIR/_nucleus-test" &&
  grep -q -- "'--quiet\[quiet\]'" "$_COMPLETIONS_DIR/_nucleus-test" &&
  grep -q -- "'--fail-fast\[fail fast\]'" "$_COMPLETIONS_DIR/_nucleus-test" &&
  grep -q -- "'--no-fail-fast\[no fail fast\]'" "$_COMPLETIONS_DIR/_nucleus-test" &&
  grep -q -- "'--skip-steps\[skip steps\]'" "$_COMPLETIONS_DIR/_nucleus-test" &&
  grep -q -- '--help' "$_COMPLETIONS_DIR/_nucleus-utils" &&
  ! grep -qE -- '--(arg|argjson)' "$_COMPLETIONS_DIR/_nucleus-config" &&
  ! grep -qE -- "'--(arg|argjson|max-time|contimeout|import|all)\[" "$_COMPLETIONS_DIR"/_nucleus*; then
  assert_pass "gen-completions: flag extraction matches the authoritative table"
else
  assert_fail "gen-completions: flag extraction" "flag set deviates from the authoritative table"
fi

# 9. Merged subcommand coverage: parent completion files enumerate their
#    subcommands after the command-surface merge (check packer/sh/pwsh,
#    gc cleanup-nix/preferences, apply health-check/audit-store, cloud
#    setup/reset/sync/repair, update lockfile).
_sub_ok=1
for _s in packer sh pwsh; do
  grep -qw -- "$_s" "$_COMPLETIONS_DIR/_nucleus-check" || {
    assert_fail "gen-completions: subcommand" "check missing $_s"
    _sub_ok=0
  }
done
for _s in cleanup-nix preferences; do
  grep -qw -- "$_s" "$_COMPLETIONS_DIR/_nucleus-gc" || {
    assert_fail "gen-completions: subcommand" "gc missing $_s"
    _sub_ok=0
  }
done
for _s in health-check audit-store; do
  grep -qw -- "$_s" "$_COMPLETIONS_DIR/_nucleus-apply" || {
    assert_fail "gen-completions: subcommand" "apply missing $_s"
    _sub_ok=0
  }
done
for _s in setup reset sync repair; do
  grep -qw -- "$_s" "$_COMPLETIONS_DIR/_nucleus-cloud" || {
    assert_fail "gen-completions: subcommand" "cloud missing $_s"
    _sub_ok=0
  }
done
for _s in update lockfile; do
  grep -qw -- "$_s" "$_COMPLETIONS_DIR/_nucleus-update" || {
    assert_fail "gen-completions: subcommand" "update missing $_s"
    _sub_ok=0
  }
done
if [ "$_sub_ok" -eq 1 ]; then
  assert_pass "gen-completions: merged subcommands covered by parent completions"
fi

# 7. _nucleus dispatcher completes `nucleus-<TAB>` with every command name.
_disp_file="$_COMPLETIONS_DIR/_nucleus"
if grep -q '^#compdef nucleus-$' "$_disp_file" &&
  grep -qw 'apply' "$_disp_file" &&
  grep -qw 'check' "$_disp_file" &&
  grep -qw 'cloud' "$_disp_file" &&
  grep -qw 'gc' "$_disp_file" &&
  grep -qw 'update' "$_disp_file" &&
  grep -qw 'vm' "$_disp_file"; then
  assert_pass "gen-completions: _nucleus dispatcher lists commands"
else
  assert_fail "gen-completions: _nucleus dispatcher" "missing #compdef nucleus- or command names"
fi

# 10. Description text with shell metacharacters must survive BOTH quoting
#     layers of a generated file: the single-quoted spec word parsed by the
#     shell, and the double-quoted description that _arguments evals out of the
#     ((...)) action. Regression: an unescaped ' ended the spec word early, so
#     the file stopped being valid zsh and the command lost its whole
#     completion. Holding ' " $ in one fixture also pins the escape ORDER (the
#     single-quote layer runs last, so it cannot reintroduce an expansion).
#     The stub repo root keeps this independent of live usage() text.
_fx_repo="$_tmp_stub_repo/repo"
mkdir -p "$_fx_repo/scripts"
for _cmd in "${_NUCLEUS_COMMANDS[@]}"; do
  {
    printf '#!/usr/bin/env bash\n'
    # shellcheck disable=SC2016 # reason: the stub's own shell expands this literal text; the test must not.
    printf 'case "${1:-}" in\n'
    printf -- '--help)\n'
    printf -- "  echo 'usage: nucleus-%s'\n" "$_cmd"
    printf -- '  echo\n'
    printf -- "  echo '  --flag  Some flag'\n"
    printf -- '  ;;\n'
    printf 'esac\n'
  } >"$_fx_repo/scripts/$_cmd.sh"
done
_fx_desc="Strip a file's \"\$HOME\" metadata"
{
  printf '#!/usr/bin/env bash\n'
  # shellcheck disable=SC2016 # reason: the stub's own shell expands this literal text; the test must not.
  printf 'case "${1:-}" in\n'
  printf -- '--help)\n'
  printf -- "  echo 'usage: nucleus-utils'\n"
  printf -- '  echo\n'
  # A quoted heredoc keeps the fixture's own shell from expanding $ or quotes.
  printf "  cat <<'DESC'\n"
  printf '  optimize-pdf  %s\n' "$_fx_desc"
  printf 'DESC\n'
  printf -- '  ;;\n'
  printf 'esac\n'
} >"$_fx_repo/scripts/utils.sh"

# _fx_decode <generated-file> — print the description the file's own two quoting
# layers yield for the subcommand spec, mirroring how _arguments splits the spec
# into its third field and evals the ((...)) action content.
_fx_decode() {
  local _spec
  _spec="$(grep -oE "'1:subcommand:.*'" "$1" | head -n1)" || return 1
  [ -n "$_spec" ] || return 1
  printf '%s\n' "$_spec" | zsh -c '
    eval "spec=$(cat)"
    action="${spec#*:*:}"
    eval "ws=( ${action[3,-3]} )"
    printf "%s\n" "${ws[2]}"
  '
}

_fx_gen_rc=0
NUCLEUS_REPO_ROOT="$_fx_repo" bash "$_gen_script" >/dev/null 2>&1 || _fx_gen_rc=$?
_fx_file="$_fx_repo/src/modules/completions/zsh/_nucleus-utils"
if [ "$_fx_gen_rc" -ne 0 ]; then
  assert_fail "gen-completions: metacharacters in a subcommand description" "generator exited $_fx_gen_rc against the stub repo root"
elif ! command -v zsh >/dev/null 2>&1; then
  assert_skip "gen-completions: metacharacters in a subcommand description" "zsh not available"
else
  # check-suppress:suppression_doc: zsh -n stderr is not needed; the exit code decides the assertion.
  if zsh -n "$_fx_file" 2>/dev/null; then
    assert_pass "gen-completions: metacharacters keep the generated file valid zsh"
  else
    assert_fail "gen-completions: metacharacter syntax" "generated $_fx_file fails zsh -n"
  fi
  if _fx_decoded="$(_fx_decode "$_fx_file")" && [ "$_fx_decoded" = "$_fx_desc" ]; then
    assert_pass "gen-completions: metacharacters survive both quoting layers"
  else
    assert_fail "gen-completions: metacharacter round-trip" "expected '$_fx_desc', got '${_fx_decoded-}'"
  fi
fi

finish_tests
