#!/usr/bin/env bash
# Tests for src/scripts/completions/gen-completions.sh: --help contract, --check determinism,
# idempotent regeneration, 22-command coverage, generated headers + zsh syntax,
# bump-lockfile --list-* dynamic wiring, and flag-extraction correctness pins.

set -euo pipefail

SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"
REPO_ROOT="$(CDPATH='' cd -- "$SCRIPT_DIR/../.." && pwd -P)"
# shellcheck source=./test-lib.sh
. "$SCRIPT_DIR/test-lib.sh"

TESTS_SKIPPED=0

assert_skip() {
  local test_name="$1"
  local reason="$2"
  printf '%s⊘%s %s: %s\n' "$YELLOW" "$NC" "$test_name" "$reason"
  ((++TESTS_SKIPPED))
}

cd "$REPO_ROOT"

_gen_script="src/scripts/completions/gen-completions.sh"
_COMPLETIONS_DIR="src/modules/completions/zsh"

# The canonical nucleus-* command set (alphabetical) — must match the generator.
_NUCLEUS_COMMANDS=(ai apply audit-store bootstrap bump-lockfile check check-packer check-pwsh check-sh cleanup-nix cloud-setup config gc gs-pdf-opt health-check replica-reset replica-sync service-watchdog svc test update vm)

# 1. --help exits 0 and prints a usage: line.
if _help_out="$(bash "$_gen_script" --help 2>&1)" && printf '%s\n' "$_help_out" | grep -q '^usage: '; then
  assert_pass "gen-completions: --help exits 0 and prints usage line"
else
  assert_fail "gen-completions: --help contract" "exit code or usage line missing"
fi

# 2. Regenerate the tree, then --check must exit 0.
if bash "$_gen_script" >/dev/null 2>&1 && bash "$_gen_script" --check >/dev/null 2>&1; then
  assert_pass "gen-completions: generate then --check exits 0"
else
  assert_fail "gen-completions: generate + --check" "non-zero exit"
fi

# 3. Idempotency: a second generate is byte-identical (git-free comparison).
_tmp_snapshot="$(mktemp -d)"
trap 'rm -rf "$_tmp_snapshot"' EXIT
cp -R "$_COMPLETIONS_DIR/." "$_tmp_snapshot/"
if bash "$_gen_script" >/dev/null 2>&1 && diff -rq "$_tmp_snapshot" "$_COMPLETIONS_DIR" >/dev/null 2>&1; then
  assert_pass "gen-completions: regeneration is idempotent"
else
  assert_fail "gen-completions: idempotency" "files changed after regenerate"
fi

# 4. Coverage: every command has a zsh completion file.
_coverage_ok=1
for _cmd in "${_NUCLEUS_COMMANDS[@]}"; do
  if [ ! -f "$_COMPLETIONS_DIR/_nucleus-$_cmd" ]; then
    assert_fail "gen-completions: coverage" "missing $_COMPLETIONS_DIR/_nucleus-$_cmd"
    _coverage_ok=0
  fi
done
if [ "$_coverage_ok" -eq 1 ]; then
  assert_pass "gen-completions: all ${#_NUCLEUS_COMMANDS[@]} commands have zsh completion files"
fi

# 5. Generated headers + zsh syntax (skipped when zsh is unavailable).
if command -v zsh >/dev/null 2>&1; then
  _gen_ok=1
  for _zsh_f in "$_COMPLETIONS_DIR"/_nucleus "$_COMPLETIONS_DIR"/_nucleus-*; do
    [ -f "$_zsh_f" ] || continue
    _name="$(basename "$_zsh_f")"
    if ! grep -q '^# GENERATED by src/scripts/completions/gen-completions.sh' "$_zsh_f"; then
      assert_fail "gen-completions: generated header" "$_name lacks GENERATED header"
      _gen_ok=0
    fi
    # check-suppress:suppression_doc: zsh -n stderr is not needed; the exit code decides the assertion.
    if ! zsh -n "$_zsh_f" 2>/dev/null; then
      assert_fail "gen-completions: zsh -n" "$_name syntax error"
      _gen_ok=0
    fi
  done
  if [ "$_gen_ok" -eq 1 ]; then
    assert_pass "gen-completions: all generated files have headers and pass zsh -n"
  fi
else
  assert_skip "gen-completions: zsh syntax check" "zsh not available"
fi

# 6. bump-lockfile dynamic value completion via --list-sections.
if grep -q "_call_program 'sections' nucleus-bump-lockfile --list-sections" "$_COMPLETIONS_DIR/_nucleus-bump-lockfile" &&
  grep -q -- '--sections:section name:->sections' "$_COMPLETIONS_DIR/_nucleus-bump-lockfile"; then
  assert_pass "gen-completions: bump-lockfile --sections dynamic wiring"
else
  assert_fail "gen-completions: bump-lockfile --sections wiring" "missing _call_program/->sections"
fi

# 8. Flag extraction correctness: usage-line + body flags land in the spec,
#    corrected sets are pinned (apply's 12, test's -q group, health-check's 6,
#    gs-pdf-opt --rm-bak), and no jq/rclone/curl tool flags leak into any file.
if [ "$(grep -cE "^  '--" "$_COMPLETIONS_DIR/_nucleus-apply")" -eq 12 ] &&
  grep -q -- "'--ai-sync\[ai sync\]'" "$_COMPLETIONS_DIR/_nucleus-apply" &&
  grep -q -- "'-q\[q\]'" "$_COMPLETIONS_DIR/_nucleus-test" &&
  grep -q -- "'--quiet\[quiet\]'" "$_COMPLETIONS_DIR/_nucleus-test" &&
  grep -q -- "'--fail-fast\[fail fast\]'" "$_COMPLETIONS_DIR/_nucleus-test" &&
  grep -q -- "'--no-fail-fast\[no fail fast\]'" "$_COMPLETIONS_DIR/_nucleus-test" &&
  grep -q -- "'--skip-steps\[skip steps\]'" "$_COMPLETIONS_DIR/_nucleus-test" &&
  [ "$(grep -cE "^  '--" "$_COMPLETIONS_DIR/_nucleus-health-check")" -eq 6 ] &&
  grep -q -- "'--min-free-bytes\[min free bytes\]'" "$_COMPLETIONS_DIR/_nucleus-health-check" &&
  grep -q -- "'--rm-bak\[rm bak\]'" "$_COMPLETIONS_DIR/_nucleus-gs-pdf-opt" &&
  ! grep -q -- "'--remove-backup" "$_COMPLETIONS_DIR/_nucleus-gs-pdf-opt" &&
  ! grep -qE -- '--(arg|argjson)' "$_COMPLETIONS_DIR/_nucleus-config" &&
  ! grep -qE -- "'--(arg|argjson|max-time|contimeout|import|all)\[" "$_COMPLETIONS_DIR"/_nucleus*; then
  assert_pass "gen-completions: flag extraction matches the authoritative table"
else
  assert_fail "gen-completions: flag extraction" "flag set deviates from the authoritative table"
fi

# 7. _nucleus dispatcher completes `nucleus-<TAB>` with every command name.
_disp_file="$_COMPLETIONS_DIR/_nucleus"
if grep -q '^#compdef nucleus-$' "$_disp_file" &&
  grep -qw 'audit-store' "$_disp_file" &&
  grep -qw 'cleanup-nix' "$_disp_file" &&
  grep -qw 'service-watchdog' "$_disp_file" &&
  grep -qw 'bump-lockfile' "$_disp_file" &&
  grep -qw 'vm' "$_disp_file"; then
  assert_pass "gen-completions: _nucleus dispatcher lists commands"
else
  assert_fail "gen-completions: _nucleus dispatcher" "missing #compdef nucleus- or command names"
fi

# Summary
echo ""
if [ "$TESTS_FAILED" -gt 0 ]; then
  echo "gen-completions tests: $TESTS_FAILED failed, $TESTS_PASSED passed"
  exit 1
elif [ "$TESTS_SKIPPED" -gt 0 ]; then
  echo "gen-completions tests: all $TESTS_PASSED passed, $TESTS_SKIPPED skipped"
else
  echo "gen-completions tests: all $TESTS_PASSED passed"
fi
