#!/usr/bin/env bash
# Test: always-install prek hook installer (src/scripts/install-prek-hooks.sh).

set -euo pipefail

SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"
# shellcheck source=./test-lib.sh
. "$SCRIPT_DIR/test-lib.sh"

INSTALL_SCRIPT="$SCRIPT_DIR/../../src/scripts/install-prek-hooks.sh"

TEST_DIR="$(mktemp -d)"
FAKE_PREK_DIR="$TEST_DIR/fake-prek"
PREK_LOG="$TEST_DIR/prek.log"
STDOUT_LOG="$TEST_DIR/stdout.log"
STDERR_LOG="$TEST_DIR/stderr.log"
trap 'rm -rf "$TEST_DIR"' EXIT

mkdir -p "$FAKE_PREK_DIR"
: >"$PREK_LOG"
: >"$STDOUT_LOG"
: >"$STDERR_LOG"

# Fake prek: records "$PWD $*" (cwd and args) per invocation; prints nothing.
cat >"$FAKE_PREK_DIR/prek" <<'EOF'
#!/usr/bin/env bash
printf '%s %s\n' "$PWD" "$*" >>"$FAKE_PREK_LOG"
exit "${FAKE_PREK_EXIT:-0}"
EOF
chmod +x "$FAKE_PREK_DIR/prek"

run_installer() {
  local repo="$1"
  (cd / && PATH="$FAKE_PREK_DIR:$PATH" FAKE_PREK_LOG="$PREK_LOG" \
    "$INSTALL_SCRIPT" --repo-root "$repo" >"$STDOUT_LOG" 2>"$STDERR_LOG")
}

test_no_prek_toml() {
  local repo="$TEST_DIR/repo-no-prek"
  local reason=""
  mkdir -p "$repo"
  if ! run_installer "$repo"; then
    reason="installer exited non-zero without prek.toml"
  fi
  if [ -s "$PREK_LOG" ]; then
    reason="$reason; prek invoked without prek.toml"
  fi
  if [ -n "$reason" ]; then
    assert_fail "no_prek_toml" "$reason"
  else
    assert_pass "no_prek_toml"
  fi
}

test_installs_with_cwd_repo_root() {
  local repo="$TEST_DIR/repo-basic"
  local reason=""
  local first_line
  mkdir -p "$repo"
  : >"$repo/prek.toml"
  if ! run_installer "$repo"; then
    reason="installer exited non-zero with prek.toml"
  fi
  first_line="$(head -n 1 "$PREK_LOG")"
  if [ "$first_line" != "$repo install --quiet" ]; then
    reason="$reason; expected '$repo install --quiet', got '$first_line'"
  fi
  if [ -n "$reason" ]; then
    assert_fail "installs_with_cwd_repo_root" "$reason"
  else
    assert_pass "installs_with_cwd_repo_root"
  fi
}

test_failure_exits_1() {
  local repo="$TEST_DIR/repo-failure"
  local reason=""
  mkdir -p "$repo"
  : >"$repo/prek.toml"
  if FAKE_PREK_EXIT=3 run_installer "$repo"; then
    reason="installer exited 0 despite prek failure"
  fi
  if ! grep -q "failed to install hooks" "$STDERR_LOG"; then
    reason="$reason; stderr missing 'failed to install hooks': $(cat "$STDERR_LOG")"
  fi
  if [ -n "$reason" ]; then
    assert_fail "failure_exits_1" "$reason"
  else
    assert_pass "failure_exits_1"
  fi
}

test_submodule_git_file() {
  local repo="$TEST_DIR/repo-submodule"
  local reason=""
  local last_line
  mkdir -p "$repo"
  : >"$repo/prek.toml"
  touch "$repo/.git"
  if ! run_installer "$repo"; then
    reason="installer exited non-zero with .git as a file"
  fi
  last_line="$(tail -n 1 "$PREK_LOG")"
  if [ "$last_line" != "$repo install --quiet" ]; then
    reason="$reason; expected '$repo install --quiet', got '$last_line'"
  fi
  if [ -n "$reason" ]; then
    assert_fail "submodule_git_file" "$reason"
  else
    assert_pass "submodule_git_file"
  fi
}

test_already_installed_silent() {
  local repo="$TEST_DIR/repo-already"
  local reason=""
  mkdir -p "$repo" "$repo/.git/hooks"
  : >"$repo/prek.toml"
  printf '%s\n' '# File generated by prek' >"$repo/.git/hooks/commit-msg"
  if ! run_installer "$repo"; then
    reason="installer exited non-zero with hooks already present"
  fi
  if [ -s "$STDOUT_LOG" ] || [ -s "$STDERR_LOG" ]; then
    reason="$reason; installer emitted output (stdout: $(cat "$STDOUT_LOG"), stderr: $(cat "$STDERR_LOG"))"
  fi
  if [ "$(tail -n 1 "$PREK_LOG")" != "$repo install --quiet" ]; then
    reason="$reason; prek not invoked"
  fi
  if [ -n "$reason" ]; then
    assert_fail "already_installed_silent" "$reason"
  else
    assert_pass "already_installed_silent"
  fi
}

test_passes_quiet_flag() {
  local last_line
  last_line="$(tail -n 1 "$PREK_LOG")"
  if [[ "$last_line" == *"install --quiet" ]]; then
    assert_pass "passes_quiet_flag"
  else
    assert_fail "passes_quiet_flag" "invocation lacks --quiet: '$last_line'"
  fi
}

test_fresh_repo_no_git() {
  local repo="$TEST_DIR/repo-fresh"
  local reason=""
  local last_line
  mkdir -p "$repo"
  : >"$repo/prek.toml"
  if ! run_installer "$repo"; then
    reason="installer exited non-zero on fresh repo without .git"
  fi
  last_line="$(tail -n 1 "$PREK_LOG")"
  if [ "$last_line" != "$repo install --quiet" ]; then
    reason="$reason; expected '$repo install --quiet', got '$last_line'"
  fi
  if [ -n "$reason" ]; then
    assert_fail "fresh_repo_no_git" "$reason"
  else
    assert_pass "fresh_repo_no_git"
  fi
}

main() {
  test_no_prek_toml
  test_installs_with_cwd_repo_root
  test_failure_exits_1
  test_submodule_git_file
  test_already_installed_silent
  test_passes_quiet_flag
  test_fresh_repo_no_git

  echo "install-prek-hooks-tests.sh: $TESTS_PASSED passed, $TESTS_FAILED failed"
  if [ "$TESTS_FAILED" -gt 0 ]; then
    exit 1
  fi
  exit 0
}

main "$@"
