#!/usr/bin/env bash
# Golden render tests for the VM host-kind templates (start-host.ps1,
# stop-posix.sh, stop-host.ps1): rendering each template with the same sed
# chains vm.sh uses must produce helper scripts with no leftover double-underscore
# token placeholders, no legacy {{TOKEN}}, and the expected commands for each
# host kind. The windows-qemu stop render is compared byte-for-byte against the
# canonical golden content (formerly a 36-line heredoc in vm.sh).
#
# Run with: bash tests/scripts/vm-template-render-tests.sh

SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(CDPATH='' cd -- "$SCRIPT_DIR/../.." && pwd -P)"
TEMPLATES_DIR="$REPO_ROOT/src/vms/templates"

_failures=0

render_template() { # render_template <template> <outfile> <-e expr...>
  local _template="$1" _out="$2"; shift 2
  sed "$@" "$TEMPLATES_DIR/$_template" >"$_out"
}

assert_no_tokens() { # assert_no_tokens <file> <label>
  local _file="$1" _label="$2"
  if grep -q '__[A-Z][A-Z_]*__' "$_file"; then
    echo "FAIL: $_label contains leftover __TOKEN__ placeholders:"
    grep -n '__[A-Z][A-Z_]*__' "$_file" | head -5
    _failures=$((_failures + 1))
  fi
  if grep -q '{{' "$_file"; then
    echo "FAIL: $_label contains legacy {{ placeholders"
    grep -n '{{' "$_file" | head -5
    _failures=$((_failures + 1))
  fi
  return 0
}

assert_contains() { # assert_contains <needle> <file> <label>
  local _needle="$1" _file="$2" _label="$3"
  if ! grep -qF -- "$_needle" "$_file"; then
    echo "FAIL: $_label does not contain expected text: $_needle"
    _failures=$((_failures + 1))
  fi
}

_tmp="$(mktemp -d)"
trap 'rm -rf "$_tmp"' EXIT

test_start_host_ps1_render() {
  render_template start-host.ps1 "$_tmp/start-testvm.ps1" \
    -e "s|__HOST_KIND__|darwin-tart|g" \
    -e "s|__VM_NAME__|testvm|g" \
    -e "s|__VM_DISPLAY__|Test VM|g" \
    -e "s|__VM_DIR__|/virtual machines|g"
  assert_no_tokens "$_tmp/start-testvm.ps1" "start-host.ps1 (darwin-tart)"
  assert_contains "switch ('darwin-tart')" "$_tmp/start-testvm.ps1" "start-host.ps1 (darwin-tart)"
  # shellcheck disable=SC2016 # reason: literal $ in single quotes is intentional for grep -F needle matching of rendered PowerShell
  assert_contains '& tart run $vmName' "$_tmp/start-testvm.ps1" "start-host.ps1 (darwin-tart)"
  # shellcheck disable=SC2016 # reason: literal $ in single quotes is intentional for grep -F needle matching of rendered PowerShell
  assert_contains '$vmName = '\''testvm'\''' "$_tmp/start-testvm.ps1" "start-host.ps1 (darwin-tart)"
}

test_stop_posix_sh_render() {
  render_template stop-posix.sh "$_tmp/stop-testvm.sh" \
    -e "s|__HOST_KIND__|darwin-utm|g" \
    -e "s|__VM_NAME__|testvm|g" \
    -e "s|__VM_DISPLAY__|Test VM|g"
  assert_no_tokens "$_tmp/stop-testvm.sh" "stop-posix.sh (darwin-utm)"
  assert_contains 'HOST_KIND="darwin-utm"' "$_tmp/stop-testvm.sh" "stop-posix.sh (darwin-utm)"
  assert_contains 'exec utmctl stop "Test VM"' "$_tmp/stop-testvm.sh" "stop-posix.sh (darwin-utm)"
  assert_contains 'exec tart stop "testvm"' "$_tmp/stop-testvm.sh" "stop-posix.sh (darwin-utm)"
}

test_stop_host_ps1_windows_golden() {
  render_template stop-host.ps1 "$_tmp/stop-winvm.ps1" \
    -e "s|__HOST_KIND__|windows-qemu|g" \
    -e "s|__VM_NAME__|winvm|g"
  assert_no_tokens "$_tmp/stop-winvm.ps1" "stop-host.ps1 (windows-qemu)"

  # Byte-for-byte golden comparison against the canonical content (formerly a
  # 36-line heredoc in vm.sh; backtick-escaped statement dollars were a latent
  # bug, so the golden content uses plain dollars).
  cat >"$_tmp/stop-winvm.golden" <<'GOLDEN'
# Generated by nucleus-vm setup — stop-winvm.ps1. Dispatches to the
# hypervisor selected by windows-qemu (Tart, UTM, libvirt, or QEMU on
# Windows), substituted at VM creation time. VM_NAME is similarly substituted.
#Requires -Version 7.4

$vmName = 'winvm'
$qemuPipe = "\\.\pipe\qga-$vmName"

switch ('windows-qemu') {
  'darwin-tart' {
    & tart stop $vmName
  }
  'darwin-utm' {
    if (Get-Command 'utmctl' -ErrorAction SilentlyContinue) {  # check-suppress:suppression_doc: utmctl optional; absent warns
      & utmctl stop $vmName
    } else {
      Write-Warning "utmctl not found; VM may still be running: $vmName"
    }
  }
  'nixos-libvirt' {
    & virsh shutdown $vmName > $null 2>&1
    if ($LASTEXITCODE -ne 0) {
      & virsh destroy $vmName
    }
  }
  'windows-qemu' {
    $ErrorActionPreference = 'Stop'

    # Try QEMU guest agent shutdown first.
    if (Test-Path -LiteralPath $qemuPipe -PathType Leaf) {
      try {
        Write-Output "Sending guest shutdown via QEMU GA: $vmName"
        # Write the QEMU GA command to the pipe (simplified; a full QMP client
        # would be required for the actual protocol exchange).
        return
      } catch {
        Write-Warning "QEMU GA shutdown failed: $_"
      }
    }

    # Fallback: kill the QEMU process.
    $proc = Get-Process -Name 'qemu-system-*' -ErrorAction SilentlyContinue | Where-Object {
      $_.CommandLine -match "$vmName"
    }
    if ($proc) {
      Write-Output "Stopping QEMU process for VM: $vmName"
      $proc | Stop-Process -Force
    } else {
      Write-Warning "No running QEMU process found for VM: $vmName"
    }
  }
  default {
    Write-Error "nucleus-vm: unknown host kind: windows-qemu"
    exit 1
  }
}
GOLDEN
  # Normalize CRLF (gitattributes sets *.ps1 to CRLF) so the byte comparison
  # is EOL-agnostic; the golden content below is LF.
  tr -d '\r' <"$_tmp/stop-winvm.ps1" >"$_tmp/stop-winvm.lf"
  if ! cmp -s "$_tmp/stop-winvm.golden" "$_tmp/stop-winvm.lf"; then
    echo "FAIL: stop-host.ps1 (windows-qemu) render differs from golden content:"
    diff -u "$_tmp/stop-winvm.golden" "$_tmp/stop-winvm.lf" | head -40
    _failures=$((_failures + 1))
  fi
}

test_start_host_ps1_render
test_stop_posix_sh_render
test_stop_host_ps1_windows_golden

if [ "$_failures" -eq 0 ]; then
  echo "vm-template-render-tests: all checks passed"
  exit 0
fi
echo "vm-template-render-tests: $_failures check(s) failed" >&2
exit 1
